
//
// designTokens/ios-swift/DesignSystem+Enum.swift
//

// Do not edit directly
// Generated on Sun, 05 Feb 2023 17:23:17 GMT


import UIKit

public enum DesignSystemEnum {
    public static let baseBoldFontFamily = Roboto
    public static let baseBoldFontSize = 14
    public static let baseBoldFontWeight = Bold
    public static let baseBoldLineHeight = 140%
    public static let baseMediumFontFamily = Roboto
    public static let baseMediumFontSize = 14
    public static let baseMediumFontWeight = Medium
    public static let baseMediumLineHeight = 140%
    public static let baseRegularFontFamily = Roboto
    public static let baseRegularFontSize = 14
    public static let baseRegularFontWeight = Regular
    public static let baseRegularLineHeight = 140%
    public static let baseSemiBoldFontFamily = Roboto
    public static let baseSemiBoldFontSize = 14
    public static let baseSemiBoldFontWeight = SemiBold
    public static let baseSemiBoldLineHeight = 140%
    public static let borderRadiusLg = 12
    public static let borderRadiusMd = 8
    public static let borderRadiusSm = 4
    public static let borderRadiusXl = 16
    public static let borderRadiusXxl = 20
    public static let borderRadiusXxxl = 24
    public static let borderWidth1 = 1
    public static let borderWidth2 = 2
    public static let buttonBorderDangerActive = [object Object]
    public static let buttonBorderDangerHover = [object Object]
    public static let buttonBorderPrimaryActive = [object Object]
    public static let buttonBorderPrimaryHover = [object Object]
    public static let buttonBorderRadiusSm = 4
    public static let buttonBorderRadiusXxxl = 24
    public static let buttonBorderSecondaryActive = [object Object]
    public static let buttonBorderSecondaryHover = [object Object]
    public static let buttonBorderSuccessActive = [object Object]
    public static let buttonBorderSuccessHover = [object Object]
    public static let buttonBorderWidthSm = 1
    public static let buttonDangerActive = UIColor(red: 0.929, green: 0.188, blue: 0.188, alpha: 1)
    public static let buttonDangerClick = UIColor(red: 0.973, green: 0.667, blue: 0.667, alpha: 1)
    public static let buttonDangerHover = UIColor(red: 0.651, green: 0.133, blue: 0.133, alpha: 1)
    public static let buttonDangerHoverAlt = UIColor(red: 0.992, green: 0.918, blue: 0.918, alpha: 1)
    public static let buttonDisabled = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    public static let buttonInfoActive = UIColor(red: 0.118, green: 0.667, blue: 0.976, alpha: 1)
    public static let buttonInfoClick = UIColor(red: 0.639, green: 0.863, blue: 0.992, alpha: 1)
    public static let buttonInfoHover = UIColor(red: 0.082, green: 0.467, blue: 0.682, alpha: 1)
    public static let buttonInfoHoverAlt = UIColor(red: 0.914, green: 0.969, blue: 0.996, alpha: 1)
    public static let buttonPrimaryActive = UIColor(red: 0.337, green: 0.710, blue: 0.737, alpha: 1)
    public static let buttonPrimaryClick = UIColor(red: 0.729, green: 0.882, blue: 0.894, alpha: 1)
    public static let buttonPrimaryHover = UIColor(red: 0.235, green: 0.498, blue: 0.518, alpha: 1)
    public static let buttonPrimaryHoverAlt = UIColor(red: 0.933, green: 0.973, blue: 0.973, alpha: 1)
    public static let buttonSecondaryActive = UIColor(red: 0.937, green: 0.545, blue: 0.427, alpha: 1)
    public static let buttonSecondaryClick = UIColor(red: 0.973, green: 0.812, blue: 0.765, alpha: 1)
    public static let buttonSecondaryHover = UIColor(red: 0.655, green: 0.380, blue: 0.298, alpha: 1)
    public static let buttonSecondaryHoverAlt = UIColor(red: 0.992, green: 0.953, blue: 0.941, alpha: 1)
    public static let buttonSuccessActive = UIColor(red: 0.475, green: 0.757, blue: 0.192, alpha: 1)
    public static let buttonSuccessClick = UIColor(red: 0.784, green: 0.902, blue: 0.671, alpha: 1)
    public static let buttonSuccessHover = UIColor(red: 0.333, green: 0.529, blue: 0.133, alpha: 1)
    public static let buttonSuccessHoverAlt = UIColor(red: 0.949, green: 0.976, blue: 0.918, alpha: 1)
    public static let buttonTextWhite = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorAccentA100 = UIColor(red: 0.616, green: 0.831, blue: 0.847, alpha: 1)
    public static let colorAccentA200 = UIColor(red: 0.451, green: 0.761, blue: 0.780, alpha: 1)
    public static let colorAccentA300 = UIColor(red: 0.337, green: 0.710, blue: 0.737, alpha: 1)
    public static let colorAccentA400 = UIColor(red: 0.235, green: 0.498, blue: 0.518, alpha: 1)
    public static let colorAccentA50 = UIColor(red: 0.933, green: 0.973, blue: 0.973, alpha: 1)
    public static let colorAccentA500 = UIColor(red: 0.204, green: 0.431, blue: 0.451, alpha: 1)
    public static let colorAccentA75 = UIColor(red: 0.729, green: 0.882, blue: 0.894, alpha: 1)
    public static let colorBlack = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorBody = UIColor(red: 0.024, green: 0.071, blue: 0.086, alpha: 1)
    public static let colorDangerD100 = UIColor(red: 0.961, green: 0.529, blue: 0.529, alpha: 1)
    public static let colorDangerD200 = UIColor(red: 0.941, green: 0.325, blue: 0.325, alpha: 1)
    public static let colorDangerD300 = UIColor(red: 0.929, green: 0.188, blue: 0.188, alpha: 1)
    public static let colorDangerD400 = UIColor(red: 0.651, green: 0.133, blue: 0.133, alpha: 1)
    public static let colorDangerD50 = UIColor(red: 0.992, green: 0.918, blue: 0.918, alpha: 1)
    public static let colorDangerD500 = UIColor(red: 0.569, green: 0.114, blue: 0.114, alpha: 1)
    public static let colorDangerD75 = UIColor(red: 0.973, green: 0.667, blue: 0.667, alpha: 1)
    public static let colorInfoI100 = UIColor(red: 0.490, green: 0.808, blue: 0.988, alpha: 1)
    public static let colorInfoI200 = UIColor(red: 0.267, green: 0.722, blue: 0.980, alpha: 1)
    public static let colorInfoI300 = UIColor(red: 0.118, green: 0.667, blue: 0.976, alpha: 1)
    public static let colorInfoI400 = UIColor(red: 0.082, green: 0.467, blue: 0.682, alpha: 1)
    public static let colorInfoI50 = UIColor(red: 0.914, green: 0.969, blue: 0.996, alpha: 1)
    public static let colorInfoI500 = UIColor(red: 0.071, green: 0.408, blue: 0.596, alpha: 1)
    public static let colorInfoI75 = UIColor(red: 0.639, green: 0.863, blue: 0.992, alpha: 1)
    public static let colorNeutralN0 = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorNeutralN10 = UIColor(red: 0.980, green: 0.980, blue: 0.984, alpha: 1)
    public static let colorNeutralN100 = UIColor(red: 0.471, green: 0.494, blue: 0.584, alpha: 1)
    public static let colorNeutralN20 = UIColor(red: 0.961, green: 0.961, blue: 0.969, alpha: 1)
    public static let colorNeutralN200 = UIColor(red: 0.412, green: 0.439, blue: 0.537, alpha: 1)
    public static let colorNeutralN30 = UIColor(red: 0.922, green: 0.925, blue: 0.937, alpha: 1)
    public static let colorNeutralN300 = UIColor(red: 0.353, green: 0.384, blue: 0.490, alpha: 1)
    public static let colorNeutralN40 = UIColor(red: 0.875, green: 0.878, blue: 0.898, alpha: 1)
    public static let colorNeutralN400 = UIColor(red: 0.306, green: 0.337, blue: 0.451, alpha: 1)
    public static let colorNeutralN50 = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    public static let colorNeutralN500 = UIColor(red: 0.247, green: 0.282, blue: 0.404, alpha: 1)
    public static let colorNeutralN60 = UIColor(red: 0.698, green: 0.710, blue: 0.761, alpha: 1)
    public static let colorNeutralN600 = UIColor(red: 0.196, green: 0.235, blue: 0.365, alpha: 1)
    public static let colorNeutralN70 = UIColor(red: 0.647, green: 0.663, blue: 0.722, alpha: 1)
    public static let colorNeutralN700 = UIColor(red: 0.129, green: 0.169, blue: 0.314, alpha: 1)
    public static let colorNeutralN80 = UIColor(red: 0.588, green: 0.608, blue: 0.675, alpha: 1)
    public static let colorNeutralN800 = UIColor(red: 0.071, green: 0.114, blue: 0.267, alpha: 1)
    public static let colorNeutralN90 = UIColor(red: 0.529, green: 0.553, blue: 0.627, alpha: 1)
    public static let colorNeutralN900 = UIColor(red: 0.020, green: 0.067, blue: 0.227, alpha: 1)
    public static let colorPrimaryP100 = UIColor(red: 0.424, green: 0.545, blue: 0.580, alpha: 1)
    public static let colorPrimaryP200 = UIColor(red: 0.176, green: 0.349, blue: 0.400, alpha: 1)
    public static let colorPrimaryP300 = UIColor(red: 0.008, green: 0.216, blue: 0.278, alpha: 1)
    public static let colorPrimaryP400 = UIColor(red: 0.004, green: 0.153, blue: 0.196, alpha: 1)
    public static let colorPrimaryP50 = UIColor(red: 0.902, green: 0.922, blue: 0.929, alpha: 1)
    public static let colorPrimaryP500 = UIColor(red: 0.004, green: 0.133, blue: 0.169, alpha: 1)
    public static let colorPrimaryP75 = UIColor(red: 0.592, green: 0.678, blue: 0.706, alpha: 1)
    public static let colorSecondaryS100 = UIColor(red: 0.965, green: 0.737, blue: 0.667, alpha: 1)
    public static let colorSecondaryS200 = UIColor(red: 0.949, green: 0.624, blue: 0.525, alpha: 1)
    public static let colorSecondaryS300 = UIColor(red: 0.937, green: 0.545, blue: 0.427, alpha: 1)
    public static let colorSecondaryS400 = UIColor(red: 0.655, green: 0.380, blue: 0.298, alpha: 1)
    public static let colorSecondaryS50 = UIColor(red: 0.992, green: 0.953, blue: 0.941, alpha: 1)
    public static let colorSecondaryS500 = UIColor(red: 0.573, green: 0.333, blue: 0.259, alpha: 1)
    public static let colorSecondaryS75 = UIColor(red: 0.973, green: 0.812, blue: 0.765, alpha: 1)
    public static let colorSuccessS100 = UIColor(red: 0.694, green: 0.859, blue: 0.533, alpha: 1)
    public static let colorSuccessS200 = UIColor(red: 0.565, green: 0.800, blue: 0.329, alpha: 1)
    public static let colorSuccessS300 = UIColor(red: 0.475, green: 0.757, blue: 0.192, alpha: 1)
    public static let colorSuccessS400 = UIColor(red: 0.333, green: 0.529, blue: 0.133, alpha: 1)
    public static let colorSuccessS50 = UIColor(red: 0.949, green: 0.976, blue: 0.918, alpha: 1)
    public static let colorSuccessS500 = UIColor(red: 0.290, green: 0.463, blue: 0.118, alpha: 1)
    public static let colorSuccessS75 = UIColor(red: 0.784, green: 0.902, blue: 0.671, alpha: 1)
    public static let colorWarningW100 = UIColor(red: 1.000, green: 0.859, blue: 0.525, alpha: 1)
    public static let colorWarningW200 = UIColor(red: 1.000, green: 0.800, blue: 0.322, alpha: 1)
    public static let colorWarningW300 = UIColor(red: 1.000, green: 0.757, blue: 0.180, alpha: 1)
    public static let colorWarningW400 = UIColor(red: 0.702, green: 0.529, blue: 0.125, alpha: 1)
    public static let colorWarningW50 = UIColor(red: 1.000, green: 0.976, blue: 0.918, alpha: 1)
    public static let colorWarningW500 = UIColor(red: 0.612, green: 0.463, blue: 0.110, alpha: 1)
    public static let colorWarningW75 = UIColor(red: 1.000, green: 0.902, blue: 0.663, alpha: 1)
    public static let colorWhite = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let fontDefaultColor = UIColor(red: 0.024, green: 0.071, blue: 0.086, alpha: 1)
    public static let fontFamily = Roboto
    public static let fontShadeColor = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    public static let fontSize0 = 10
    public static let fontSize1 = 11
    public static let fontSize10 = 32
    public static let fontSize2 = 12
    public static let fontSize3 = 14
    public static let fontSize4 = 16
    public static let fontSize5 = 18
    public static let fontSize6 = 20
    public static let fontSize7 = 22
    public static let fontSize8 = 25
    public static let fontSize9 = 28
    public static let fontWeightBold = Bold
    public static let fontWeightItalic = Italic
    public static let fontWeightMedium = Medium
    public static let fontWeightRegular = Regular
    public static let fontWeightSemiBold = SemiBold
    public static let h1BoldFontFamily = Roboto
    public static let h1BoldFontSize = 32
    public static let h1BoldFontWeight = Bold
    public static let h1BoldLineHeight = 120%
    public static let h1MediumFontFamily = Roboto
    public static let h1MediumFontSize = 32
    public static let h1MediumFontWeight = Medium
    public static let h1MediumLineHeight = 120%
    public static let h1RegularFontFamily = Roboto
    public static let h1RegularFontSize = 32
    public static let h1RegularFontWeight = Regular
    public static let h1RegularLineHeight = 120%
    public static let h1SemiBoldFontFamily = Roboto
    public static let h1SemiBoldFontSize = 32
    public static let h1SemiBoldFontWeight = SemiBold
    public static let h1SemiBoldLineHeight = 120%
    public static let h2BoldFontFamily = Roboto
    public static let h2BoldFontSize = 28
    public static let h2BoldFontWeight = Bold
    public static let h2BoldLineHeight = 120%
    public static let h2MediumFontFamily = Roboto
    public static let h2MediumFontSize = 28
    public static let h2MediumFontWeight = Medium
    public static let h2MediumLineHeight = 120%
    public static let h2RegularFontFamily = Roboto
    public static let h2RegularFontSize = 28
    public static let h2RegularFontWeight = Regular
    public static let h2RegularLineHeight = 120%
    public static let h2SemiBoldFontFamily = Roboto
    public static let h2SemiBoldFontSize = 28
    public static let h2SemiBoldFontWeight = SemiBold
    public static let h2SemiBoldLineHeight = 120%
    public static let h3BoldFontFamily = Roboto
    public static let h3BoldFontSize = 25
    public static let h3BoldFontWeight = Bold
    public static let h3BoldLineHeight = 120%
    public static let h3MediumFontFamily = Roboto
    public static let h3MediumFontSize = 25
    public static let h3MediumFontWeight = Medium
    public static let h3MediumLineHeight = 120%
    public static let h3RegularFontFamily = Roboto
    public static let h3RegularFontSize = 25
    public static let h3RegularFontWeight = Regular
    public static let h3RegularLineHeight = 120%
    public static let h3SemiBoldFontFamily = Roboto
    public static let h3SemiBoldFontSize = 25
    public static let h3SemiBoldFontWeight = SemiBold
    public static let h3SemiBoldLineHeight = 120%
    public static let h4BoldFontFamily = Roboto
    public static let h4BoldFontSize = 22
    public static let h4BoldFontWeight = Bold
    public static let h4BoldLineHeight = 120%
    public static let h4MediumFontFamily = Roboto
    public static let h4MediumFontSize = 22
    public static let h4MediumFontWeight = Medium
    public static let h4MediumLineHeight = 120%
    public static let h4RegularFontFamily = Roboto
    public static let h4RegularFontSize = 22
    public static let h4RegularFontWeight = Regular
    public static let h4RegularLineHeight = 120%
    public static let h4SemiBoldFontFamily = Roboto
    public static let h4SemiBoldFontSize = 22
    public static let h4SemiBoldFontWeight = SemiBold
    public static let h4SemiBoldLineHeight = 120%
    public static let h5BoldFontFamily = Roboto
    public static let h5BoldFontSize = 20
    public static let h5BoldFontWeight = Bold
    public static let h5BoldLineHeight = 120%
    public static let h5MediumFontFamily = Roboto
    public static let h5MediumFontSize = 20
    public static let h5MediumFontWeight = Medium
    public static let h5MediumLineHeight = 120%
    public static let h5RegularFontFamily = Roboto
    public static let h5RegularFontSize = 20
    public static let h5RegularFontWeight = Regular
    public static let h5RegularLineHeight = 120%
    public static let h5SemiBoldFontFamily = Roboto
    public static let h5SemiBoldFontSize = 20
    public static let h5SemiBoldFontWeight = SemiBold
    public static let h5SemiBoldLineHeight = 120%
    public static let h6BoldFontFamily = Roboto
    public static let h6BoldFontSize = 18
    public static let h6BoldFontWeight = Bold
    public static let h6BoldLineHeight = 120%
    public static let h6MediumFontFamily = Roboto
    public static let h6MediumFontSize = 18
    public static let h6MediumFontWeight = Medium
    public static let h6MediumLineHeight = 120%
    public static let h6RegularFontFamily = Roboto
    public static let h6RegularFontSize = 18
    public static let h6RegularFontWeight = Regular
    public static let h6RegularLineHeight = 120%
    public static let h6SemiBoldFontFamily = Roboto
    public static let h6SemiBoldFontSize = 18
    public static let h6SemiBoldFontWeight = SemiBold
    public static let h6SemiBoldLineHeight = 120%
    public static let labelBoldFontFamily = Roboto
    public static let labelBoldFontSize = 11
    public static let labelBoldFontWeight = Bold
    public static let labelBoldLineHeight = 120%
    public static let labelMediumFontFamily = Roboto
    public static let labelMediumFontSize = 11
    public static let labelMediumFontWeight = Medium
    public static let labelMediumLineHeight = 120%
    public static let labelRegularFontFamily = Roboto
    public static let labelRegularFontSize = 11
    public static let labelRegularFontWeight = Regular
    public static let labelRegularLineHeight = 120%
    public static let labelSemiBoldFontFamily = Roboto
    public static let labelSemiBoldFontSize = 11
    public static let labelSemiBoldFontWeight = SemiBold
    public static let labelSemiBoldLineHeight = 120%
    public static let largeBoldFontFamily = Roboto
    public static let largeBoldFontSize = 16
    public static let largeBoldFontWeight = Bold
    public static let largeBoldLineHeight = 140%
    public static let largeMediumFontFamily = Roboto
    public static let largeMediumFontSize = 16
    public static let largeMediumFontWeight = Medium
    public static let largeMediumLineHeight = 140%
    public static let largeRegularFontFamily = Roboto
    public static let largeRegularFontSize = 16
    public static let largeRegularFontWeight = Regular
    public static let largeRegularLineHeight = 140%
    public static let largeSemiBoldFontFamily = Roboto
    public static let largeSemiBoldFontSize = 16
    public static let largeSemiBoldFontWeight = SemiBold
    public static let largeSemiBoldLineHeight = 140%
    public static let layoutBackgroundAccent = UIColor(red: 0.933, green: 0.973, blue: 0.973, alpha: 1)
    public static let layoutBackgroundN10 = UIColor(red: 0.980, green: 0.980, blue: 0.984, alpha: 1)
    public static let layoutBackgroundN20 = UIColor(red: 0.961, green: 0.961, blue: 0.969, alpha: 1)
    public static let layoutBackgroundN30 = UIColor(red: 0.922, green: 0.925, blue: 0.937, alpha: 1)
    public static let layoutBackgroundN40 = UIColor(red: 0.875, green: 0.878, blue: 0.898, alpha: 1)
    public static let layoutBackgroundN50 = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    public static let layoutBackgroundPrimary = UIColor(red: 0.902, green: 0.922, blue: 0.929, alpha: 1)
    public static let layoutBackgroundSecondary = UIColor(red: 0.992, green: 0.953, blue: 0.941, alpha: 1)
    public static let layoutBorderRadiusLg = 12
    public static let layoutBorderRadiusMd = 8
    public static let layoutBorderRadiusSm = 4
    public static let layoutBorderRadiusXl = 16
    public static let layoutSpacing12 = 12
    public static let layoutSpacing16 = 16
    public static let layoutSpacing2 = 2
    public static let layoutSpacing20 = 20
    public static let layoutSpacing24 = 24
    public static let layoutSpacing28 = 28
    public static let layoutSpacing32 = 32
    public static let layoutSpacing36 = 36
    public static let layoutSpacing4 = 4
    public static let layoutSpacing40 = 40
    public static let layoutSpacing44 = 44
    public static let layoutSpacing48 = 48
    public static let layoutSpacing52 = 52
    public static let layoutSpacing56 = 56
    public static let layoutSpacing60 = 60
    public static let layoutSpacing8 = 8
    public static let letterSpacing0 = 0%
    public static let lineHeight120 = 120%
    public static let lineHeight140 = 140%
    public static let opacity10 = 10%
    public static let opacity100 = 100%
    public static let opacity20 = 20%
    public static let opacity30 = 30%
    public static let opacity40 = 40%
    public static let opacity50 = 50%
    public static let opacity60 = 60%
    public static let opacity70 = 70%
    public static let opacity80 = 80%
    public static let opacity90 = 90%
    public static let size400 = CGFloat(6400.00)
    public static let size500 = CGFloat(8000.00)
    public static let size600 = CGFloat(9600.00)
    public static let size700 = CGFloat(11200.00)
    public static let size800 = CGFloat(12800.00)
    public static let size900 = CGFloat(14400.00)
    public static let smallBoldFontFamily = Roboto
    public static let smallBoldFontSize = 12
    public static let smallBoldFontWeight = Bold
    public static let smallBoldLineHeight = 140%
    public static let smallMediumFontFamily = Roboto
    public static let smallMediumFontSize = 12
    public static let smallMediumFontWeight = Medium
    public static let smallMediumLineHeight = 140%
    public static let smallRegularFontFamily = Roboto
    public static let smallRegularFontSize = 12
    public static let smallRegularFontWeight = Regular
    public static let smallRegularLineHeight = 140%
    public static let smallSemiBoldFontFamily = Roboto
    public static let smallSemiBoldFontSize = 12
    public static let smallSemiBoldFontWeight = SemiBold
    public static let smallSemiBoldLineHeight = 140%
    public static let spacing12 = 12
    public static let spacing16 = 16
    public static let spacing2 = 2
    public static let spacing20 = 20
    public static let spacing24 = 24
    public static let spacing28 = 28
    public static let spacing32 = 32
    public static let spacing36 = 36
    public static let spacing4 = 4
    public static let spacing40 = 40
    public static let spacing44 = 44
    public static let spacing48 = 48
    public static let spacing52 = 52
    public static let spacing56 = 56
    public static let spacing60 = 60
    public static let spacing64 = 64
    public static let spacing68 = 68
    public static let spacing72 = 72
    public static let spacing76 = 76
    public static let spacing8 = 8
    public static let spacing80 = 80
    public static let textCaseNone = none
    public static let textCaseUppercase = uppercase
    public static let textDecorationNone = none
    public static let textDecorationUnderline = underline
    public static let tokenSetOrder0 = globals
    public static let tokenSetOrder1 = 0-core/__layout
    public static let tokenSetOrder2 = 0-core/__buttons
    public static let tokenSetOrder3 = 0-core/__typography
    public static let tokenSetOrder4 = 1-components
    public static let xSmallBoldFontFamily = Roboto
    public static let xSmallBoldFontSize = 10
    public static let xSmallBoldFontWeight = Bold
    public static let xSmallBoldLineHeight = 120%
    public static let xSmallMediumFontFamily = Roboto
    public static let xSmallMediumFontSize = 10
    public static let xSmallMediumFontWeight = Medium
    public static let xSmallMediumLineHeight = 120%
    public static let xSmallRegularFontFamily = Roboto
    public static let xSmallRegularFontSize = 10
    public static let xSmallRegularFontWeight = Regular
    public static let xSmallRegularLineHeight = 120%
    public static let xSmallSemiBoldFontFamily = Roboto
    public static let xSmallSemiBoldFontSize = 10
    public static let xSmallSemiBoldFontWeight = SemiBold
    public static let xSmallSemiBoldLineHeight = 120%
}
