
//
// designTokens/ios-swift/DesignSystem+Enum.swift
//

// Do not edit directly
// Generated on Fri, 03 Feb 2023 14:50:47 GMT


import UIKit

public enum DesignSystemEnum {
    public static let baseBoldFontFamily = Roboto
    public static let baseBoldFontSize = 14
    public static let baseBoldFontWeight = Bold
    public static let baseBoldLetterSpacing = 0%
    public static let baseBoldLineHeight = 140%
    public static let baseBoldParagraphIndent = 0
    public static let baseBoldParagraphSpacing = 0
    public static let baseBoldTextCase = none
    public static let baseBoldTextDecoration = none
    public static let baseItalicFontFamily = Roboto
    public static let baseItalicFontSize = 14
    public static let baseItalicFontWeight = Italic
    public static let baseItalicLetterSpacing = 0%
    public static let baseItalicLineHeight = 140%
    public static let baseItalicParagraphIndent = 0
    public static let baseItalicParagraphSpacing = 0
    public static let baseItalicTextCase = none
    public static let baseItalicTextDecoration = none
    public static let baseMediumFontFamily = Roboto
    public static let baseMediumFontSize = 14
    public static let baseMediumFontWeight = Medium
    public static let baseMediumLetterSpacing = 0%
    public static let baseMediumLineHeight = 140%
    public static let baseMediumParagraphIndent = 0
    public static let baseMediumParagraphSpacing = 0
    public static let baseMediumTextCase = none
    public static let baseMediumTextDecoration = none
    public static let baseRegularFontFamily = Roboto
    public static let baseRegularFontSize = 14
    public static let baseRegularFontWeight = Regular
    public static let baseRegularLetterSpacing = 0%
    public static let baseRegularLineHeight = 140%
    public static let baseRegularParagraphIndent = 0
    public static let baseRegularParagraphSpacing = 0
    public static let baseRegularTextCase = none
    public static let baseRegularTextDecoration = none
    public static let baseSemiBoldFontFamily = Roboto
    public static let baseSemiBoldFontSize = 14
    public static let baseSemiBoldFontWeight = SemiBold
    public static let baseSemiBoldLetterSpacing = 0%
    public static let baseSemiBoldLineHeight = 140%
    public static let baseSemiBoldParagraphIndent = 0
    public static let baseSemiBoldParagraphSpacing = 0
    public static let baseSemiBoldTextCase = none
    public static let baseSemiBoldTextDecoration = none
    public static let borderRadiusLg = 12
    public static let borderRadiusMd = 8
    public static let borderRadiusSm = 4
    public static let borderRadiusXl = 16
    public static let borderRadiusXxl = 20
    public static let borderRadiusXxxl = 24
    public static let borderWidth1 = 1
    public static let borderWidth2 = 2
    public static let buttonPrimaryBackgroundColor = UIColor(red: 0.337, green: 0.710, blue: 0.737, alpha: 1)
    public static let colorAccentA100 = UIColor(red: 0.616, green: 0.831, blue: 0.847, alpha: 1)
    public static let colorAccentA200 = UIColor(red: 0.451, green: 0.761, blue: 0.780, alpha: 1)
    public static let colorAccentA300 = UIColor(red: 0.337, green: 0.710, blue: 0.737, alpha: 1)
    public static let colorAccentA400 = UIColor(red: 0.235, green: 0.498, blue: 0.518, alpha: 1)
    public static let colorAccentA50 = UIColor(red: 0.933, green: 0.973, blue: 0.973, alpha: 1)
    public static let colorAccentA500 = UIColor(red: 0.204, green: 0.431, blue: 0.451, alpha: 1)
    public static let colorAccentA75 = UIColor(red: 0.729, green: 0.882, blue: 0.894, alpha: 1)
    public static let colorBlack = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorBody = UIColor(red: 0.024, green: 0.071, blue: 0.086, alpha: 1)
    public static let colorDangerD100 = UIColor(red: 0.961, green: 0.529, blue: 0.529, alpha: 1)
    public static let colorDangerD200 = UIColor(red: 0.941, green: 0.325, blue: 0.325, alpha: 1)
    public static let colorDangerD300 = UIColor(red: 0.929, green: 0.188, blue: 0.188, alpha: 1)
    public static let colorDangerD400 = UIColor(red: 0.651, green: 0.133, blue: 0.133, alpha: 1)
    public static let colorDangerD50 = UIColor(red: 0.992, green: 0.918, blue: 0.918, alpha: 1)
    public static let colorDangerD500 = UIColor(red: 0.569, green: 0.114, blue: 0.114, alpha: 1)
    public static let colorDangerD75 = UIColor(red: 0.973, green: 0.667, blue: 0.667, alpha: 1)
    public static let colorInfoI100 = UIColor(red: 0.490, green: 0.808, blue: 0.988, alpha: 1)
    public static let colorInfoI200 = UIColor(red: 0.267, green: 0.722, blue: 0.980, alpha: 1)
    public static let colorInfoI300 = UIColor(red: 0.118, green: 0.667, blue: 0.976, alpha: 1)
    public static let colorInfoI400 = UIColor(red: 0.082, green: 0.467, blue: 0.682, alpha: 1)
    public static let colorInfoI50 = UIColor(red: 0.914, green: 0.969, blue: 0.996, alpha: 1)
    public static let colorInfoI500 = UIColor(red: 0.071, green: 0.408, blue: 0.596, alpha: 1)
    public static let colorInfoI75 = UIColor(red: 0.639, green: 0.863, blue: 0.992, alpha: 1)
    public static let colorNeutralN0 = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorNeutralN10 = UIColor(red: 0.980, green: 0.980, blue: 0.984, alpha: 1)
    public static let colorNeutralN100 = UIColor(red: 0.471, green: 0.494, blue: 0.584, alpha: 1)
    public static let colorNeutralN20 = UIColor(red: 0.961, green: 0.961, blue: 0.969, alpha: 1)
    public static let colorNeutralN200 = UIColor(red: 0.412, green: 0.439, blue: 0.537, alpha: 1)
    public static let colorNeutralN30 = UIColor(red: 0.922, green: 0.925, blue: 0.937, alpha: 1)
    public static let colorNeutralN300 = UIColor(red: 0.353, green: 0.384, blue: 0.490, alpha: 1)
    public static let colorNeutralN40 = UIColor(red: 0.875, green: 0.878, blue: 0.898, alpha: 1)
    public static let colorNeutralN400 = UIColor(red: 0.306, green: 0.337, blue: 0.451, alpha: 1)
    public static let colorNeutralN50 = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    public static let colorNeutralN500 = UIColor(red: 0.247, green: 0.282, blue: 0.404, alpha: 1)
    public static let colorNeutralN60 = UIColor(red: 0.698, green: 0.710, blue: 0.761, alpha: 1)
    public static let colorNeutralN600 = UIColor(red: 0.196, green: 0.235, blue: 0.365, alpha: 1)
    public static let colorNeutralN70 = UIColor(red: 0.647, green: 0.663, blue: 0.722, alpha: 1)
    public static let colorNeutralN700 = UIColor(red: 0.129, green: 0.169, blue: 0.314, alpha: 1)
    public static let colorNeutralN80 = UIColor(red: 0.588, green: 0.608, blue: 0.675, alpha: 1)
    public static let colorNeutralN800 = UIColor(red: 0.071, green: 0.114, blue: 0.267, alpha: 1)
    public static let colorNeutralN90 = UIColor(red: 0.529, green: 0.553, blue: 0.627, alpha: 1)
    public static let colorNeutralN900 = UIColor(red: 0.020, green: 0.067, blue: 0.227, alpha: 1)
    public static let colorPrimaryP100 = UIColor(red: 0.424, green: 0.545, blue: 0.580, alpha: 1)
    public static let colorPrimaryP200 = UIColor(red: 0.176, green: 0.349, blue: 0.400, alpha: 1)
    public static let colorPrimaryP300 = UIColor(red: 0.008, green: 0.216, blue: 0.278, alpha: 1)
    public static let colorPrimaryP400 = UIColor(red: 0.004, green: 0.153, blue: 0.196, alpha: 1)
    public static let colorPrimaryP50 = UIColor(red: 0.902, green: 0.922, blue: 0.929, alpha: 1)
    public static let colorPrimaryP500 = UIColor(red: 0.004, green: 0.133, blue: 0.169, alpha: 1)
    public static let colorPrimaryP75 = UIColor(red: 0.592, green: 0.678, blue: 0.706, alpha: 1)
    public static let colorSecondaryS100 = UIColor(red: 0.965, green: 0.737, blue: 0.667, alpha: 1)
    public static let colorSecondaryS200 = UIColor(red: 0.949, green: 0.624, blue: 0.525, alpha: 1)
    public static let colorSecondaryS300 = UIColor(red: 0.937, green: 0.545, blue: 0.427, alpha: 1)
    public static let colorSecondaryS400 = UIColor(red: 0.655, green: 0.380, blue: 0.298, alpha: 1)
    public static let colorSecondaryS50 = UIColor(red: 0.992, green: 0.953, blue: 0.941, alpha: 1)
    public static let colorSecondaryS500 = UIColor(red: 0.573, green: 0.333, blue: 0.259, alpha: 1)
    public static let colorSecondaryS75 = UIColor(red: 0.973, green: 0.812, blue: 0.765, alpha: 1)
    public static let colorSuccessS100 = UIColor(red: 0.694, green: 0.859, blue: 0.533, alpha: 1)
    public static let colorSuccessS200 = UIColor(red: 0.565, green: 0.800, blue: 0.329, alpha: 1)
    public static let colorSuccessS300 = UIColor(red: 0.475, green: 0.757, blue: 0.192, alpha: 1)
    public static let colorSuccessS400 = UIColor(red: 0.333, green: 0.529, blue: 0.133, alpha: 1)
    public static let colorSuccessS50 = UIColor(red: 0.949, green: 0.976, blue: 0.918, alpha: 1)
    public static let colorSuccessS500 = UIColor(red: 0.290, green: 0.463, blue: 0.118, alpha: 1)
    public static let colorSuccessS75 = UIColor(red: 0.784, green: 0.902, blue: 0.671, alpha: 1)
    public static let colorWarningW100 = UIColor(red: 1.000, green: 0.859, blue: 0.525, alpha: 1)
    public static let colorWarningW200 = UIColor(red: 1.000, green: 0.800, blue: 0.322, alpha: 1)
    public static let colorWarningW300 = UIColor(red: 1.000, green: 0.757, blue: 0.180, alpha: 1)
    public static let colorWarningW400 = UIColor(red: 0.702, green: 0.529, blue: 0.125, alpha: 1)
    public static let colorWarningW50 = UIColor(red: 1.000, green: 0.976, blue: 0.918, alpha: 1)
    public static let colorWarningW500 = UIColor(red: 0.612, green: 0.463, blue: 0.110, alpha: 1)
    public static let colorWarningW75 = UIColor(red: 1.000, green: 0.902, blue: 0.663, alpha: 1)
    public static let colorWhite = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let fontFamilyRoboto = Roboto
    public static let fontSize0 = 10
    public static let fontSize1 = 11
    public static let fontSize10 = 32
    public static let fontSize2 = 12
    public static let fontSize3 = 14
    public static let fontSize4 = 16
    public static let fontSize5 = 18
    public static let fontSize6 = 20
    public static let fontSize7 = 22
    public static let fontSize8 = 25
    public static let fontSize9 = 28
    public static let fontWeightBold = Bold
    public static let fontWeightItalic = Italic
    public static let fontWeightMedium = Medium
    public static let fontWeightRegular = Regular
    public static let fontWeightSemiBold = SemiBold
    public static let h1BoldFontFamily = Roboto
    public static let h1BoldFontSize = 32
    public static let h1BoldFontWeight = Bold
    public static let h1BoldLetterSpacing = 0%
    public static let h1BoldLineHeight = 120%
    public static let h1BoldParagraphIndent = 0
    public static let h1BoldParagraphSpacing = 0
    public static let h1BoldTextCase = none
    public static let h1BoldTextDecoration = none
    public static let h1MediumFontFamily = Roboto
    public static let h1MediumFontSize = 32
    public static let h1MediumFontWeight = Medium
    public static let h1MediumLetterSpacing = 0%
    public static let h1MediumLineHeight = 120%
    public static let h1MediumParagraphIndent = 0
    public static let h1MediumParagraphSpacing = 0
    public static let h1MediumTextCase = none
    public static let h1MediumTextDecoration = none
    public static let h1RegularFontFamily = Roboto
    public static let h1RegularFontSize = 32
    public static let h1RegularFontWeight = Regular
    public static let h1RegularLetterSpacing = 0%
    public static let h1RegularLineHeight = 120%
    public static let h1RegularParagraphIndent = 0
    public static let h1RegularParagraphSpacing = 0
    public static let h1RegularTextCase = none
    public static let h1RegularTextDecoration = none
    public static let h1SemiBoldFontFamily = Roboto
    public static let h1SemiBoldFontSize = 32
    public static let h1SemiBoldFontWeight = SemiBold
    public static let h1SemiBoldLetterSpacing = 0%
    public static let h1SemiBoldLineHeight = 120%
    public static let h1SemiBoldParagraphIndent = 0
    public static let h1SemiBoldParagraphSpacing = 0
    public static let h1SemiBoldTextCase = none
    public static let h1SemiBoldTextDecoration = none
    public static let h2BoldFontFamily = Roboto
    public static let h2BoldFontSize = 28
    public static let h2BoldFontWeight = Bold
    public static let h2BoldLetterSpacing = 0%
    public static let h2BoldLineHeight = 120%
    public static let h2BoldParagraphIndent = 0
    public static let h2BoldParagraphSpacing = 0
    public static let h2BoldTextCase = none
    public static let h2BoldTextDecoration = none
    public static let h2MediumFontFamily = Roboto
    public static let h2MediumFontSize = 28
    public static let h2MediumFontWeight = Medium
    public static let h2MediumLetterSpacing = 0%
    public static let h2MediumLineHeight = 120%
    public static let h2MediumParagraphIndent = 0
    public static let h2MediumParagraphSpacing = 0
    public static let h2MediumTextCase = none
    public static let h2MediumTextDecoration = none
    public static let h2RegularFontFamily = Roboto
    public static let h2RegularFontSize = 28
    public static let h2RegularFontWeight = Regular
    public static let h2RegularLetterSpacing = 0%
    public static let h2RegularLineHeight = 120%
    public static let h2RegularParagraphIndent = 0
    public static let h2RegularParagraphSpacing = 0
    public static let h2RegularTextCase = none
    public static let h2RegularTextDecoration = none
    public static let h2SemiBoldFontFamily = Roboto
    public static let h2SemiBoldFontSize = 28
    public static let h2SemiBoldFontWeight = SemiBold
    public static let h2SemiBoldLetterSpacing = 0%
    public static let h2SemiBoldLineHeight = 120%
    public static let h2SemiBoldParagraphIndent = 0
    public static let h2SemiBoldParagraphSpacing = 0
    public static let h2SemiBoldTextCase = none
    public static let h2SemiBoldTextDecoration = none
    public static let h3BoldFontFamily = Roboto
    public static let h3BoldFontSize = 25
    public static let h3BoldFontWeight = Bold
    public static let h3BoldLetterSpacing = 0%
    public static let h3BoldLineHeight = 120%
    public static let h3BoldParagraphIndent = 0
    public static let h3BoldParagraphSpacing = 0
    public static let h3BoldTextCase = none
    public static let h3BoldTextDecoration = none
    public static let h3MediumFontFamily = Roboto
    public static let h3MediumFontSize = 25
    public static let h3MediumFontWeight = Medium
    public static let h3MediumLetterSpacing = 0%
    public static let h3MediumLineHeight = 120%
    public static let h3MediumParagraphIndent = 0
    public static let h3MediumParagraphSpacing = 0
    public static let h3MediumTextCase = none
    public static let h3MediumTextDecoration = none
    public static let h3RegularFontFamily = Roboto
    public static let h3RegularFontSize = 25
    public static let h3RegularFontWeight = Regular
    public static let h3RegularLetterSpacing = 0%
    public static let h3RegularLineHeight = 120%
    public static let h3RegularParagraphIndent = 0
    public static let h3RegularParagraphSpacing = 0
    public static let h3RegularTextCase = none
    public static let h3RegularTextDecoration = none
    public static let h3SemiBoldFontFamily = Roboto
    public static let h3SemiBoldFontSize = 25
    public static let h3SemiBoldFontWeight = SemiBold
    public static let h3SemiBoldLetterSpacing = 0%
    public static let h3SemiBoldLineHeight = 120%
    public static let h3SemiBoldParagraphIndent = 0
    public static let h3SemiBoldParagraphSpacing = 0
    public static let h3SemiBoldTextCase = none
    public static let h3SemiBoldTextDecoration = none
    public static let h4BoldFontFamily = Roboto
    public static let h4BoldFontSize = 22
    public static let h4BoldFontWeight = Bold
    public static let h4BoldLetterSpacing = 0%
    public static let h4BoldLineHeight = 120%
    public static let h4BoldParagraphIndent = 0
    public static let h4BoldParagraphSpacing = 0
    public static let h4BoldTextCase = none
    public static let h4BoldTextDecoration = none
    public static let h4MediumFontFamily = Roboto
    public static let h4MediumFontSize = 22
    public static let h4MediumFontWeight = Medium
    public static let h4MediumLetterSpacing = 0%
    public static let h4MediumLineHeight = 120%
    public static let h4MediumParagraphIndent = 0
    public static let h4MediumParagraphSpacing = 0
    public static let h4MediumTextCase = none
    public static let h4MediumTextDecoration = none
    public static let h4RegularFontFamily = Roboto
    public static let h4RegularFontSize = 22
    public static let h4RegularFontWeight = Regular
    public static let h4RegularLetterSpacing = 0%
    public static let h4RegularLineHeight = 120%
    public static let h4RegularParagraphIndent = 0
    public static let h4RegularParagraphSpacing = 0
    public static let h4RegularTextCase = none
    public static let h4RegularTextDecoration = none
    public static let h4SemiBoldFontFamily = Roboto
    public static let h4SemiBoldFontSize = 22
    public static let h4SemiBoldFontWeight = SemiBold
    public static let h4SemiBoldLetterSpacing = 0%
    public static let h4SemiBoldLineHeight = 120%
    public static let h4SemiBoldParagraphIndent = 0
    public static let h4SemiBoldParagraphSpacing = 0
    public static let h4SemiBoldTextCase = none
    public static let h4SemiBoldTextDecoration = none
    public static let h5BoldFontFamily = Roboto
    public static let h5BoldFontSize = 20
    public static let h5BoldFontWeight = Bold
    public static let h5BoldLetterSpacing = 0%
    public static let h5BoldLineHeight = 120%
    public static let h5BoldParagraphIndent = 0
    public static let h5BoldParagraphSpacing = 0
    public static let h5BoldTextCase = none
    public static let h5BoldTextDecoration = none
    public static let h5ItalicFontFamily = Roboto
    public static let h5ItalicFontSize = 20
    public static let h5ItalicFontWeight = Italic
    public static let h5ItalicLetterSpacing = 0%
    public static let h5ItalicLineHeight = 120%
    public static let h5ItalicParagraphIndent = 0
    public static let h5ItalicParagraphSpacing = 0
    public static let h5ItalicTextCase = none
    public static let h5ItalicTextDecoration = none
    public static let h5MediumFontFamily = Roboto
    public static let h5MediumFontSize = 20
    public static let h5MediumFontWeight = Medium
    public static let h5MediumLetterSpacing = 0%
    public static let h5MediumLineHeight = 120%
    public static let h5MediumParagraphIndent = 0
    public static let h5MediumParagraphSpacing = 0
    public static let h5MediumTextCase = none
    public static let h5MediumTextDecoration = none
    public static let h5RegularFontFamily = Roboto
    public static let h5RegularFontSize = 20
    public static let h5RegularFontWeight = Regular
    public static let h5RegularLetterSpacing = 0%
    public static let h5RegularLineHeight = 120%
    public static let h5RegularParagraphIndent = 0
    public static let h5RegularParagraphSpacing = 0
    public static let h5RegularTextCase = none
    public static let h5RegularTextDecoration = none
    public static let h5SemiBoldFontFamily = Roboto
    public static let h5SemiBoldFontSize = 20
    public static let h5SemiBoldFontWeight = SemiBold
    public static let h5SemiBoldLetterSpacing = 0%
    public static let h5SemiBoldLineHeight = 120%
    public static let h5SemiBoldParagraphIndent = 0
    public static let h5SemiBoldParagraphSpacing = 0
    public static let h5SemiBoldTextCase = none
    public static let h5SemiBoldTextDecoration = none
    public static let h6BoldFontFamily = Roboto
    public static let h6BoldFontSize = 18
    public static let h6BoldFontWeight = Bold
    public static let h6BoldLetterSpacing = 0%
    public static let h6BoldLineHeight = 120%
    public static let h6BoldParagraphIndent = 0
    public static let h6BoldParagraphSpacing = 0
    public static let h6BoldTextCase = none
    public static let h6BoldTextDecoration = none
    public static let h6ItalicFontFamily = Roboto
    public static let h6ItalicFontSize = 18
    public static let h6ItalicFontWeight = Italic
    public static let h6ItalicLetterSpacing = 0%
    public static let h6ItalicLineHeight = 120%
    public static let h6ItalicParagraphIndent = 0
    public static let h6ItalicParagraphSpacing = 0
    public static let h6ItalicTextCase = none
    public static let h6ItalicTextDecoration = none
    public static let h6MediumFontFamily = Roboto
    public static let h6MediumFontSize = 18
    public static let h6MediumFontWeight = Medium
    public static let h6MediumLetterSpacing = 0%
    public static let h6MediumLineHeight = 120%
    public static let h6MediumParagraphIndent = 0
    public static let h6MediumParagraphSpacing = 0
    public static let h6MediumTextCase = none
    public static let h6MediumTextDecoration = none
    public static let h6RegularFontFamily = Roboto
    public static let h6RegularFontSize = 18
    public static let h6RegularFontWeight = Regular
    public static let h6RegularLetterSpacing = 0%
    public static let h6RegularLineHeight = 120%
    public static let h6RegularParagraphIndent = 0
    public static let h6RegularParagraphSpacing = 0
    public static let h6RegularTextCase = none
    public static let h6RegularTextDecoration = none
    public static let h6SemiBoldFontFamily = Roboto
    public static let h6SemiBoldFontSize = 18
    public static let h6SemiBoldFontWeight = SemiBold
    public static let h6SemiBoldLetterSpacing = 0%
    public static let h6SemiBoldLineHeight = 120%
    public static let h6SemiBoldParagraphIndent = 0
    public static let h6SemiBoldParagraphSpacing = 0
    public static let h6SemiBoldTextCase = none
    public static let h6SemiBoldTextDecoration = none
    public static let labelBoldFontFamily = Roboto
    public static let labelBoldFontSize = 11
    public static let labelBoldFontWeight = Bold
    public static let labelBoldLetterSpacing = 0%
    public static let labelBoldLineHeight = 120%
    public static let labelBoldParagraphIndent = 0
    public static let labelBoldParagraphSpacing = 0
    public static let labelBoldTextCase = none
    public static let labelBoldTextDecoration = none
    public static let labelItalicFontFamily = Roboto
    public static let labelItalicFontSize = 11
    public static let labelItalicFontWeight = Italic
    public static let labelItalicLetterSpacing = 0%
    public static let labelItalicLineHeight = 120%
    public static let labelItalicParagraphIndent = 0
    public static let labelItalicParagraphSpacing = 0
    public static let labelItalicTextCase = none
    public static let labelItalicTextDecoration = none
    public static let labelMediumFontFamily = Roboto
    public static let labelMediumFontSize = 11
    public static let labelMediumFontWeight = Medium
    public static let labelMediumLetterSpacing = 0%
    public static let labelMediumLineHeight = 120%
    public static let labelMediumParagraphIndent = 0
    public static let labelMediumParagraphSpacing = 0
    public static let labelMediumTextCase = none
    public static let labelMediumTextDecoration = none
    public static let labelRegularFontFamily = Roboto
    public static let labelRegularFontSize = 11
    public static let labelRegularFontWeight = Regular
    public static let labelRegularLetterSpacing = 0%
    public static let labelRegularLineHeight = 120%
    public static let labelRegularParagraphIndent = 0
    public static let labelRegularParagraphSpacing = 0
    public static let labelRegularTextCase = none
    public static let labelRegularTextDecoration = none
    public static let labelSemiBoldFontFamily = Roboto
    public static let labelSemiBoldFontSize = 11
    public static let labelSemiBoldFontWeight = SemiBold
    public static let labelSemiBoldLetterSpacing = 0%
    public static let labelSemiBoldLineHeight = 120%
    public static let labelSemiBoldParagraphIndent = 0
    public static let labelSemiBoldParagraphSpacing = 0
    public static let labelSemiBoldTextCase = none
    public static let labelSemiBoldTextDecoration = none
    public static let largeBoldFontFamily = Roboto
    public static let largeBoldFontSize = 16
    public static let largeBoldFontWeight = Bold
    public static let largeBoldLetterSpacing = 0%
    public static let largeBoldLineHeight = 120%
    public static let largeBoldParagraphIndent = 0
    public static let largeBoldParagraphSpacing = 0
    public static let largeBoldTextCase = none
    public static let largeBoldTextDecoration = none
    public static let largeItalicFontFamily = Roboto
    public static let largeItalicFontSize = 16
    public static let largeItalicFontWeight = Italic
    public static let largeItalicLetterSpacing = 0%
    public static let largeItalicLineHeight = 120%
    public static let largeItalicParagraphIndent = 0
    public static let largeItalicParagraphSpacing = 0
    public static let largeItalicTextCase = none
    public static let largeItalicTextDecoration = none
    public static let largeMediumFontFamily = Roboto
    public static let largeMediumFontSize = 16
    public static let largeMediumFontWeight = Medium
    public static let largeMediumLetterSpacing = 0%
    public static let largeMediumLineHeight = 120%
    public static let largeMediumParagraphIndent = 0
    public static let largeMediumParagraphSpacing = 0
    public static let largeMediumTextCase = none
    public static let largeMediumTextDecoration = none
    public static let largeRegularFontFamily = Roboto
    public static let largeRegularFontSize = 16
    public static let largeRegularFontWeight = Regular
    public static let largeRegularLetterSpacing = 0%
    public static let largeRegularLineHeight = 120%
    public static let largeRegularParagraphIndent = 0
    public static let largeRegularParagraphSpacing = 0
    public static let largeRegularTextCase = none
    public static let largeRegularTextDecoration = none
    public static let largeSemiBoldFontFamily = Roboto
    public static let largeSemiBoldFontSize = 16
    public static let largeSemiBoldFontWeight = SemiBold
    public static let largeSemiBoldLetterSpacing = 0%
    public static let largeSemiBoldLineHeight = 120%
    public static let largeSemiBoldParagraphIndent = 0
    public static let largeSemiBoldParagraphSpacing = 0
    public static let largeSemiBoldTextCase = none
    public static let largeSemiBoldTextDecoration = none
    public static let letterSpacing0 = 0%
    public static let lineHeight120 = 120%
    public static let lineHeight140 = 140%
    public static let opacity10 = 10%
    public static let opacity100 = 100%
    public static let opacity20 = 20%
    public static let opacity30 = 30%
    public static let opacity40 = 40%
    public static let opacity50 = 50%
    public static let opacity60 = 60%
    public static let opacity70 = 70%
    public static let opacity80 = 80%
    public static let opacity90 = 90%
    public static let paragraphIndent0 = 0
    public static let paragraphSpacing0 = 0
    public static let size400 = CGFloat(6400.00)
    public static let size500 = CGFloat(8000.00)
    public static let size600 = CGFloat(9600.00)
    public static let size700 = CGFloat(11200.00)
    public static let size800 = CGFloat(12800.00)
    public static let size900 = CGFloat(14400.00)
    public static let smallBoldFontFamily = Roboto
    public static let smallBoldFontSize = 12
    public static let smallBoldFontWeight = Bold
    public static let smallBoldLetterSpacing = 0%
    public static let smallBoldLineHeight = 140%
    public static let smallBoldParagraphIndent = 0
    public static let smallBoldParagraphSpacing = 0
    public static let smallBoldTextCase = none
    public static let smallBoldTextDecoration = none
    public static let smallItalicFontFamily = Roboto
    public static let smallItalicFontSize = 12
    public static let smallItalicFontWeight = Italic
    public static let smallItalicLetterSpacing = 0%
    public static let smallItalicLineHeight = 140%
    public static let smallItalicParagraphIndent = 0
    public static let smallItalicParagraphSpacing = 0
    public static let smallItalicTextCase = none
    public static let smallItalicTextDecoration = none
    public static let smallMediumFontFamily = Roboto
    public static let smallMediumFontSize = 12
    public static let smallMediumFontWeight = Medium
    public static let smallMediumLetterSpacing = 0%
    public static let smallMediumLineHeight = 140%
    public static let smallMediumParagraphIndent = 0
    public static let smallMediumParagraphSpacing = 0
    public static let smallMediumTextCase = none
    public static let smallMediumTextDecoration = none
    public static let smallRegularFontFamily = Roboto
    public static let smallRegularFontSize = 12
    public static let smallRegularFontWeight = Regular
    public static let smallRegularLetterSpacing = 0%
    public static let smallRegularLineHeight = 140%
    public static let smallRegularParagraphIndent = 0
    public static let smallRegularParagraphSpacing = 0
    public static let smallRegularTextCase = none
    public static let smallRegularTextDecoration = none
    public static let smallSemiBoldFontFamily = Roboto
    public static let smallSemiBoldFontSize = 12
    public static let smallSemiBoldFontWeight = SemiBold
    public static let smallSemiBoldLetterSpacing = 0%
    public static let smallSemiBoldLineHeight = 140%
    public static let smallSemiBoldParagraphIndent = 0
    public static let smallSemiBoldParagraphSpacing = 0
    public static let smallSemiBoldTextCase = none
    public static let smallSemiBoldTextDecoration = none
    public static let spacing12 = 12
    public static let spacing16 = 16
    public static let spacing2 = 2
    public static let spacing20 = 20
    public static let spacing24 = 24
    public static let spacing28 = 28
    public static let spacing32 = 32
    public static let spacing36 = 36
    public static let spacing4 = 4
    public static let spacing40 = 40
    public static let spacing44 = 44
    public static let spacing48 = 48
    public static let spacing52 = 52
    public static let spacing56 = 56
    public static let spacing60 = 60
    public static let spacing64 = 64
    public static let spacing68 = 68
    public static let spacing72 = 72
    public static let spacing76 = 76
    public static let spacing8 = 8
    public static let spacing80 = 80
    public static let textCaseNone = none
    public static let textCaseUppercase = uppercase
    public static let textDecorationNone = none
    public static let textDecorationUnderline = underline
    public static let tokenSetOrder0 = core
    public static let xSmallBoldFontFamily = Roboto
    public static let xSmallBoldFontSize = 10
    public static let xSmallBoldFontWeight = Bold
    public static let xSmallBoldLetterSpacing = 0%
    public static let xSmallBoldLineHeight = 120%
    public static let xSmallBoldParagraphIndent = 0
    public static let xSmallBoldParagraphSpacing = 0
    public static let xSmallBoldTextCase = none
    public static let xSmallBoldTextDecoration = none
    public static let xSmallItalicFontFamily = Roboto
    public static let xSmallItalicFontSize = 10
    public static let xSmallItalicFontWeight = Italic
    public static let xSmallItalicLetterSpacing = 0%
    public static let xSmallItalicLineHeight = 120%
    public static let xSmallItalicParagraphIndent = 0
    public static let xSmallItalicParagraphSpacing = 0
    public static let xSmallItalicTextCase = none
    public static let xSmallItalicTextDecoration = none
    public static let xSmallMediumFontFamily = Roboto
    public static let xSmallMediumFontSize = 10
    public static let xSmallMediumFontWeight = Medium
    public static let xSmallMediumLetterSpacing = 0%
    public static let xSmallMediumLineHeight = 120%
    public static let xSmallMediumParagraphIndent = 0
    public static let xSmallMediumParagraphSpacing = 0
    public static let xSmallMediumTextCase = none
    public static let xSmallMediumTextDecoration = none
    public static let xSmallRegularFontFamily = Roboto
    public static let xSmallRegularFontSize = 10
    public static let xSmallRegularFontWeight = Regular
    public static let xSmallRegularLetterSpacing = 0%
    public static let xSmallRegularLineHeight = 120%
    public static let xSmallRegularParagraphIndent = 0
    public static let xSmallRegularParagraphSpacing = 0
    public static let xSmallRegularTextCase = none
    public static let xSmallRegularTextDecoration = none
    public static let xSmallSemiBoldFontFamily = Roboto
    public static let xSmallSemiBoldFontSize = 10
    public static let xSmallSemiBoldFontWeight = SemiBold
    public static let xSmallSemiBoldLetterSpacing = 0%
    public static let xSmallSemiBoldLineHeight = 120%
    public static let xSmallSemiBoldParagraphIndent = 0
    public static let xSmallSemiBoldParagraphSpacing = 0
    public static let xSmallSemiBoldTextCase = none
    public static let xSmallSemiBoldTextDecoration = none
}
