
//
// designTokens/ios-swift/DesignSystem+Struct.swift
//

// Do not edit directly
// Generated on Sun, 05 Feb 2023 17:30:13 GMT


import UIKit

internal struct DesignSystemStruct {
    internal static let baseBoldFontFamily = Roboto
    internal static let baseBoldFontSize = 14
    internal static let baseBoldFontWeight = Bold
    internal static let baseBoldLineHeight = 140%
    internal static let baseMediumFontFamily = Roboto
    internal static let baseMediumFontSize = 14
    internal static let baseMediumFontWeight = Medium
    internal static let baseMediumLineHeight = 140%
    internal static let baseRegularFontFamily = Roboto
    internal static let baseRegularFontSize = 14
    internal static let baseRegularFontWeight = Regular
    internal static let baseRegularLineHeight = 140%
    internal static let baseSemiBoldFontFamily = Roboto
    internal static let baseSemiBoldFontSize = 14
    internal static let baseSemiBoldFontWeight = SemiBold
    internal static let baseSemiBoldLineHeight = 140%
    internal static let borderRadiusLg = 12
    internal static let borderRadiusMd = 8
    internal static let borderRadiusSm = 4
    internal static let borderRadiusXl = 16
    internal static let borderRadiusXxl = 20
    internal static let borderRadiusXxxl = 24
    internal static let borderWidth1 = 1
    internal static let borderWidth2 = 2
    internal static let buttonBorderDangerActive = [object Object]
    internal static let buttonBorderDangerHover = [object Object]
    internal static let buttonBorderPrimaryActive = [object Object]
    internal static let buttonBorderPrimaryHover = [object Object]
    internal static let buttonBorderRadiusSm = 4
    internal static let buttonBorderRadiusXxxl = 24
    internal static let buttonBorderSecondaryActive = [object Object]
    internal static let buttonBorderSecondaryHover = [object Object]
    internal static let buttonBorderSuccessActive = [object Object]
    internal static let buttonBorderSuccessHover = [object Object]
    internal static let buttonBorderWidthSm = 1
    internal static let buttonDangerActive = UIColor(red: 0.929, green: 0.188, blue: 0.188, alpha: 1)
    internal static let buttonDangerClick = UIColor(red: 0.973, green: 0.667, blue: 0.667, alpha: 1)
    internal static let buttonDangerHover = UIColor(red: 0.651, green: 0.133, blue: 0.133, alpha: 1)
    internal static let buttonDangerHoverAlt = UIColor(red: 0.992, green: 0.918, blue: 0.918, alpha: 1)
    internal static let buttonDisabled = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    internal static let buttonInfoActive = UIColor(red: 0.118, green: 0.667, blue: 0.976, alpha: 1)
    internal static let buttonInfoClick = UIColor(red: 0.639, green: 0.863, blue: 0.992, alpha: 1)
    internal static let buttonInfoHover = UIColor(red: 0.082, green: 0.467, blue: 0.682, alpha: 1)
    internal static let buttonInfoHoverAlt = UIColor(red: 0.914, green: 0.969, blue: 0.996, alpha: 1)
    internal static let buttonPrimaryActive = UIColor(red: 0.337, green: 0.710, blue: 0.737, alpha: 1)
    internal static let buttonPrimaryClick = UIColor(red: 0.729, green: 0.882, blue: 0.894, alpha: 1)
    internal static let buttonPrimaryHover = UIColor(red: 0.235, green: 0.498, blue: 0.518, alpha: 1)
    internal static let buttonPrimaryHoverAlt = UIColor(red: 0.933, green: 0.973, blue: 0.973, alpha: 1)
    internal static let buttonSecondaryActive = UIColor(red: 0.937, green: 0.545, blue: 0.427, alpha: 1)
    internal static let buttonSecondaryClick = UIColor(red: 0.973, green: 0.812, blue: 0.765, alpha: 1)
    internal static let buttonSecondaryHover = UIColor(red: 0.655, green: 0.380, blue: 0.298, alpha: 1)
    internal static let buttonSecondaryHoverAlt = UIColor(red: 0.992, green: 0.953, blue: 0.941, alpha: 1)
    internal static let buttonSuccessActive = UIColor(red: 0.475, green: 0.757, blue: 0.192, alpha: 1)
    internal static let buttonSuccessClick = UIColor(red: 0.784, green: 0.902, blue: 0.671, alpha: 1)
    internal static let buttonSuccessHover = UIColor(red: 0.333, green: 0.529, blue: 0.133, alpha: 1)
    internal static let buttonSuccessHoverAlt = UIColor(red: 0.949, green: 0.976, blue: 0.918, alpha: 1)
    internal static let buttonTextWhite = UIColor(red: 0.573, green: 0.000, blue: 1.000, alpha: 1)
    internal static let colorAccentA100 = UIColor(red: 0.616, green: 0.831, blue: 0.847, alpha: 1)
    internal static let colorAccentA200 = UIColor(red: 0.451, green: 0.761, blue: 0.780, alpha: 1)
    internal static let colorAccentA300 = UIColor(red: 0.337, green: 0.710, blue: 0.737, alpha: 1)
    internal static let colorAccentA400 = UIColor(red: 0.235, green: 0.498, blue: 0.518, alpha: 1)
    internal static let colorAccentA50 = UIColor(red: 0.933, green: 0.973, blue: 0.973, alpha: 1)
    internal static let colorAccentA500 = UIColor(red: 0.204, green: 0.431, blue: 0.451, alpha: 1)
    internal static let colorAccentA75 = UIColor(red: 0.729, green: 0.882, blue: 0.894, alpha: 1)
    internal static let colorBlack = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorBody = UIColor(red: 0.024, green: 0.071, blue: 0.086, alpha: 1)
    internal static let colorDangerD100 = UIColor(red: 0.961, green: 0.529, blue: 0.529, alpha: 1)
    internal static let colorDangerD200 = UIColor(red: 0.941, green: 0.325, blue: 0.325, alpha: 1)
    internal static let colorDangerD300 = UIColor(red: 0.929, green: 0.188, blue: 0.188, alpha: 1)
    internal static let colorDangerD400 = UIColor(red: 0.651, green: 0.133, blue: 0.133, alpha: 1)
    internal static let colorDangerD50 = UIColor(red: 0.992, green: 0.918, blue: 0.918, alpha: 1)
    internal static let colorDangerD500 = UIColor(red: 0.569, green: 0.114, blue: 0.114, alpha: 1)
    internal static let colorDangerD75 = UIColor(red: 0.973, green: 0.667, blue: 0.667, alpha: 1)
    internal static let colorInfoI100 = UIColor(red: 0.490, green: 0.808, blue: 0.988, alpha: 1)
    internal static let colorInfoI200 = UIColor(red: 0.267, green: 0.722, blue: 0.980, alpha: 1)
    internal static let colorInfoI300 = UIColor(red: 0.118, green: 0.667, blue: 0.976, alpha: 1)
    internal static let colorInfoI400 = UIColor(red: 0.082, green: 0.467, blue: 0.682, alpha: 1)
    internal static let colorInfoI50 = UIColor(red: 0.914, green: 0.969, blue: 0.996, alpha: 1)
    internal static let colorInfoI500 = UIColor(red: 0.071, green: 0.408, blue: 0.596, alpha: 1)
    internal static let colorInfoI75 = UIColor(red: 0.639, green: 0.863, blue: 0.992, alpha: 1)
    internal static let colorNeutralN0 = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    internal static let colorNeutralN10 = UIColor(red: 0.980, green: 0.980, blue: 0.984, alpha: 1)
    internal static let colorNeutralN100 = UIColor(red: 0.471, green: 0.494, blue: 0.584, alpha: 1)
    internal static let colorNeutralN20 = UIColor(red: 0.961, green: 0.961, blue: 0.969, alpha: 1)
    internal static let colorNeutralN200 = UIColor(red: 0.412, green: 0.439, blue: 0.537, alpha: 1)
    internal static let colorNeutralN30 = UIColor(red: 0.922, green: 0.925, blue: 0.937, alpha: 1)
    internal static let colorNeutralN300 = UIColor(red: 0.353, green: 0.384, blue: 0.490, alpha: 1)
    internal static let colorNeutralN40 = UIColor(red: 0.875, green: 0.878, blue: 0.898, alpha: 1)
    internal static let colorNeutralN400 = UIColor(red: 0.306, green: 0.337, blue: 0.451, alpha: 1)
    internal static let colorNeutralN50 = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    internal static let colorNeutralN500 = UIColor(red: 0.247, green: 0.282, blue: 0.404, alpha: 1)
    internal static let colorNeutralN60 = UIColor(red: 0.698, green: 0.710, blue: 0.761, alpha: 1)
    internal static let colorNeutralN600 = UIColor(red: 0.196, green: 0.235, blue: 0.365, alpha: 1)
    internal static let colorNeutralN70 = UIColor(red: 0.647, green: 0.663, blue: 0.722, alpha: 1)
    internal static let colorNeutralN700 = UIColor(red: 0.129, green: 0.169, blue: 0.314, alpha: 1)
    internal static let colorNeutralN80 = UIColor(red: 0.588, green: 0.608, blue: 0.675, alpha: 1)
    internal static let colorNeutralN800 = UIColor(red: 0.071, green: 0.114, blue: 0.267, alpha: 1)
    internal static let colorNeutralN90 = UIColor(red: 0.529, green: 0.553, blue: 0.627, alpha: 1)
    internal static let colorNeutralN900 = UIColor(red: 0.020, green: 0.067, blue: 0.227, alpha: 1)
    internal static let colorPrimaryP100 = UIColor(red: 0.424, green: 0.545, blue: 0.580, alpha: 1)
    internal static let colorPrimaryP200 = UIColor(red: 0.176, green: 0.349, blue: 0.400, alpha: 1)
    internal static let colorPrimaryP300 = UIColor(red: 0.008, green: 0.216, blue: 0.278, alpha: 1)
    internal static let colorPrimaryP400 = UIColor(red: 0.004, green: 0.153, blue: 0.196, alpha: 1)
    internal static let colorPrimaryP50 = UIColor(red: 0.902, green: 0.922, blue: 0.929, alpha: 1)
    internal static let colorPrimaryP500 = UIColor(red: 0.004, green: 0.133, blue: 0.169, alpha: 1)
    internal static let colorPrimaryP75 = UIColor(red: 0.592, green: 0.678, blue: 0.706, alpha: 1)
    internal static let colorSecondaryS100 = UIColor(red: 0.965, green: 0.737, blue: 0.667, alpha: 1)
    internal static let colorSecondaryS200 = UIColor(red: 0.949, green: 0.624, blue: 0.525, alpha: 1)
    internal static let colorSecondaryS300 = UIColor(red: 0.937, green: 0.545, blue: 0.427, alpha: 1)
    internal static let colorSecondaryS400 = UIColor(red: 0.655, green: 0.380, blue: 0.298, alpha: 1)
    internal static let colorSecondaryS50 = UIColor(red: 0.992, green: 0.953, blue: 0.941, alpha: 1)
    internal static let colorSecondaryS500 = UIColor(red: 0.573, green: 0.333, blue: 0.259, alpha: 1)
    internal static let colorSecondaryS75 = UIColor(red: 0.973, green: 0.812, blue: 0.765, alpha: 1)
    internal static let colorSuccessS100 = UIColor(red: 0.694, green: 0.859, blue: 0.533, alpha: 1)
    internal static let colorSuccessS200 = UIColor(red: 0.565, green: 0.800, blue: 0.329, alpha: 1)
    internal static let colorSuccessS300 = UIColor(red: 0.475, green: 0.757, blue: 0.192, alpha: 1)
    internal static let colorSuccessS400 = UIColor(red: 0.333, green: 0.529, blue: 0.133, alpha: 1)
    internal static let colorSuccessS50 = UIColor(red: 0.949, green: 0.976, blue: 0.918, alpha: 1)
    internal static let colorSuccessS500 = UIColor(red: 0.290, green: 0.463, blue: 0.118, alpha: 1)
    internal static let colorSuccessS75 = UIColor(red: 0.784, green: 0.902, blue: 0.671, alpha: 1)
    internal static let colorWarningW100 = UIColor(red: 1.000, green: 0.859, blue: 0.525, alpha: 1)
    internal static let colorWarningW200 = UIColor(red: 1.000, green: 0.800, blue: 0.322, alpha: 1)
    internal static let colorWarningW300 = UIColor(red: 1.000, green: 0.757, blue: 0.180, alpha: 1)
    internal static let colorWarningW400 = UIColor(red: 0.702, green: 0.529, blue: 0.125, alpha: 1)
    internal static let colorWarningW50 = UIColor(red: 1.000, green: 0.976, blue: 0.918, alpha: 1)
    internal static let colorWarningW500 = UIColor(red: 0.612, green: 0.463, blue: 0.110, alpha: 1)
    internal static let colorWarningW75 = UIColor(red: 1.000, green: 0.902, blue: 0.663, alpha: 1)
    internal static let colorWhite = UIColor(red: 0.573, green: 0.000, blue: 1.000, alpha: 1)
    internal static let fontDefaultColor = UIColor(red: 0.024, green: 0.071, blue: 0.086, alpha: 1)
    internal static let fontFamily = Roboto
    internal static let fontShadeColor = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    internal static let fontSize0 = 10
    internal static let fontSize1 = 11
    internal static let fontSize10 = 32
    internal static let fontSize2 = 12
    internal static let fontSize3 = 14
    internal static let fontSize4 = 16
    internal static let fontSize5 = 18
    internal static let fontSize6 = 20
    internal static let fontSize7 = 22
    internal static let fontSize8 = 25
    internal static let fontSize9 = 28
    internal static let fontWeightBold = Bold
    internal static let fontWeightItalic = Italic
    internal static let fontWeightMedium = Medium
    internal static let fontWeightRegular = Regular
    internal static let fontWeightSemiBold = SemiBold
    internal static let h1BoldFontFamily = Roboto
    internal static let h1BoldFontSize = 32
    internal static let h1BoldFontWeight = Bold
    internal static let h1BoldLineHeight = 120%
    internal static let h1MediumFontFamily = Roboto
    internal static let h1MediumFontSize = 32
    internal static let h1MediumFontWeight = Medium
    internal static let h1MediumLineHeight = 120%
    internal static let h1RegularFontFamily = Roboto
    internal static let h1RegularFontSize = 32
    internal static let h1RegularFontWeight = Regular
    internal static let h1RegularLineHeight = 120%
    internal static let h1SemiBoldFontFamily = Roboto
    internal static let h1SemiBoldFontSize = 32
    internal static let h1SemiBoldFontWeight = SemiBold
    internal static let h1SemiBoldLineHeight = 120%
    internal static let h2BoldFontFamily = Roboto
    internal static let h2BoldFontSize = 28
    internal static let h2BoldFontWeight = Bold
    internal static let h2BoldLineHeight = 120%
    internal static let h2MediumFontFamily = Roboto
    internal static let h2MediumFontSize = 28
    internal static let h2MediumFontWeight = Medium
    internal static let h2MediumLineHeight = 120%
    internal static let h2RegularFontFamily = Roboto
    internal static let h2RegularFontSize = 28
    internal static let h2RegularFontWeight = Regular
    internal static let h2RegularLineHeight = 120%
    internal static let h2SemiBoldFontFamily = Roboto
    internal static let h2SemiBoldFontSize = 28
    internal static let h2SemiBoldFontWeight = SemiBold
    internal static let h2SemiBoldLineHeight = 120%
    internal static let h3BoldFontFamily = Roboto
    internal static let h3BoldFontSize = 25
    internal static let h3BoldFontWeight = Bold
    internal static let h3BoldLineHeight = 120%
    internal static let h3MediumFontFamily = Roboto
    internal static let h3MediumFontSize = 25
    internal static let h3MediumFontWeight = Medium
    internal static let h3MediumLineHeight = 120%
    internal static let h3RegularFontFamily = Roboto
    internal static let h3RegularFontSize = 25
    internal static let h3RegularFontWeight = Regular
    internal static let h3RegularLineHeight = 120%
    internal static let h3SemiBoldFontFamily = Roboto
    internal static let h3SemiBoldFontSize = 25
    internal static let h3SemiBoldFontWeight = SemiBold
    internal static let h3SemiBoldLineHeight = 120%
    internal static let h4BoldFontFamily = Roboto
    internal static let h4BoldFontSize = 22
    internal static let h4BoldFontWeight = Bold
    internal static let h4BoldLineHeight = 120%
    internal static let h4MediumFontFamily = Roboto
    internal static let h4MediumFontSize = 22
    internal static let h4MediumFontWeight = Medium
    internal static let h4MediumLineHeight = 120%
    internal static let h4RegularFontFamily = Roboto
    internal static let h4RegularFontSize = 22
    internal static let h4RegularFontWeight = Regular
    internal static let h4RegularLineHeight = 120%
    internal static let h4SemiBoldFontFamily = Roboto
    internal static let h4SemiBoldFontSize = 22
    internal static let h4SemiBoldFontWeight = SemiBold
    internal static let h4SemiBoldLineHeight = 120%
    internal static let h5BoldFontFamily = Roboto
    internal static let h5BoldFontSize = 20
    internal static let h5BoldFontWeight = Bold
    internal static let h5BoldLineHeight = 120%
    internal static let h5MediumFontFamily = Roboto
    internal static let h5MediumFontSize = 20
    internal static let h5MediumFontWeight = Medium
    internal static let h5MediumLineHeight = 120%
    internal static let h5RegularFontFamily = Roboto
    internal static let h5RegularFontSize = 20
    internal static let h5RegularFontWeight = Regular
    internal static let h5RegularLineHeight = 120%
    internal static let h5SemiBoldFontFamily = Roboto
    internal static let h5SemiBoldFontSize = 20
    internal static let h5SemiBoldFontWeight = SemiBold
    internal static let h5SemiBoldLineHeight = 120%
    internal static let h6BoldFontFamily = Roboto
    internal static let h6BoldFontSize = 18
    internal static let h6BoldFontWeight = Bold
    internal static let h6BoldLineHeight = 120%
    internal static let h6MediumFontFamily = Roboto
    internal static let h6MediumFontSize = 18
    internal static let h6MediumFontWeight = Medium
    internal static let h6MediumLineHeight = 120%
    internal static let h6RegularFontFamily = Roboto
    internal static let h6RegularFontSize = 18
    internal static let h6RegularFontWeight = Regular
    internal static let h6RegularLineHeight = 120%
    internal static let h6SemiBoldFontFamily = Roboto
    internal static let h6SemiBoldFontSize = 18
    internal static let h6SemiBoldFontWeight = SemiBold
    internal static let h6SemiBoldLineHeight = 120%
    internal static let labelBoldFontFamily = Roboto
    internal static let labelBoldFontSize = 11
    internal static let labelBoldFontWeight = Bold
    internal static let labelBoldLineHeight = 120%
    internal static let labelMediumFontFamily = Roboto
    internal static let labelMediumFontSize = 11
    internal static let labelMediumFontWeight = Medium
    internal static let labelMediumLineHeight = 120%
    internal static let labelRegularFontFamily = Roboto
    internal static let labelRegularFontSize = 11
    internal static let labelRegularFontWeight = Regular
    internal static let labelRegularLineHeight = 120%
    internal static let labelSemiBoldFontFamily = Roboto
    internal static let labelSemiBoldFontSize = 11
    internal static let labelSemiBoldFontWeight = SemiBold
    internal static let labelSemiBoldLineHeight = 120%
    internal static let largeBoldFontFamily = Roboto
    internal static let largeBoldFontSize = 16
    internal static let largeBoldFontWeight = Bold
    internal static let largeBoldLineHeight = 140%
    internal static let largeMediumFontFamily = Roboto
    internal static let largeMediumFontSize = 16
    internal static let largeMediumFontWeight = Medium
    internal static let largeMediumLineHeight = 140%
    internal static let largeRegularFontFamily = Roboto
    internal static let largeRegularFontSize = 16
    internal static let largeRegularFontWeight = Regular
    internal static let largeRegularLineHeight = 140%
    internal static let largeSemiBoldFontFamily = Roboto
    internal static let largeSemiBoldFontSize = 16
    internal static let largeSemiBoldFontWeight = SemiBold
    internal static let largeSemiBoldLineHeight = 140%
    internal static let layoutBackgroundAccent = UIColor(red: 0.933, green: 0.973, blue: 0.973, alpha: 1)
    internal static let layoutBackgroundN10 = UIColor(red: 0.980, green: 0.980, blue: 0.984, alpha: 1)
    internal static let layoutBackgroundN20 = UIColor(red: 0.961, green: 0.961, blue: 0.969, alpha: 1)
    internal static let layoutBackgroundN30 = UIColor(red: 0.922, green: 0.925, blue: 0.937, alpha: 1)
    internal static let layoutBackgroundN40 = UIColor(red: 0.875, green: 0.878, blue: 0.898, alpha: 1)
    internal static let layoutBackgroundN50 = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    internal static let layoutBackgroundPrimary = UIColor(red: 0.902, green: 0.922, blue: 0.929, alpha: 1)
    internal static let layoutBackgroundSecondary = UIColor(red: 0.992, green: 0.953, blue: 0.941, alpha: 1)
    internal static let layoutBorderRadiusLg = 12
    internal static let layoutBorderRadiusMd = 8
    internal static let layoutBorderRadiusSm = 4
    internal static let layoutBorderRadiusXl = 16
    internal static let layoutSpacing12 = 12
    internal static let layoutSpacing16 = 16
    internal static let layoutSpacing2 = 2
    internal static let layoutSpacing20 = 20
    internal static let layoutSpacing24 = 24
    internal static let layoutSpacing28 = 28
    internal static let layoutSpacing32 = 32
    internal static let layoutSpacing36 = 36
    internal static let layoutSpacing4 = 4
    internal static let layoutSpacing40 = 40
    internal static let layoutSpacing44 = 44
    internal static let layoutSpacing48 = 48
    internal static let layoutSpacing52 = 52
    internal static let layoutSpacing56 = 56
    internal static let layoutSpacing60 = 60
    internal static let layoutSpacing8 = 8
    internal static let letterSpacing0 = 0%
    internal static let lineHeight120 = 120%
    internal static let lineHeight140 = 140%
    internal static let opacity10 = 10%
    internal static let opacity100 = 100%
    internal static let opacity20 = 20%
    internal static let opacity30 = 30%
    internal static let opacity40 = 40%
    internal static let opacity50 = 50%
    internal static let opacity60 = 60%
    internal static let opacity70 = 70%
    internal static let opacity80 = 80%
    internal static let opacity90 = 90%
    internal static let size400 = CGFloat(6400.00)
    internal static let size500 = CGFloat(8000.00)
    internal static let size600 = CGFloat(9600.00)
    internal static let size700 = CGFloat(11200.00)
    internal static let size800 = CGFloat(12800.00)
    internal static let size900 = CGFloat(14400.00)
    internal static let smallBoldFontFamily = Roboto
    internal static let smallBoldFontSize = 12
    internal static let smallBoldFontWeight = Bold
    internal static let smallBoldLineHeight = 140%
    internal static let smallMediumFontFamily = Roboto
    internal static let smallMediumFontSize = 12
    internal static let smallMediumFontWeight = Medium
    internal static let smallMediumLineHeight = 140%
    internal static let smallRegularFontFamily = Roboto
    internal static let smallRegularFontSize = 12
    internal static let smallRegularFontWeight = Regular
    internal static let smallRegularLineHeight = 140%
    internal static let smallSemiBoldFontFamily = Roboto
    internal static let smallSemiBoldFontSize = 12
    internal static let smallSemiBoldFontWeight = SemiBold
    internal static let smallSemiBoldLineHeight = 140%
    internal static let spacing12 = 12
    internal static let spacing16 = 16
    internal static let spacing2 = 2
    internal static let spacing20 = 20
    internal static let spacing24 = 24
    internal static let spacing28 = 28
    internal static let spacing32 = 32
    internal static let spacing36 = 36
    internal static let spacing4 = 4
    internal static let spacing40 = 40
    internal static let spacing44 = 44
    internal static let spacing48 = 48
    internal static let spacing52 = 52
    internal static let spacing56 = 56
    internal static let spacing60 = 60
    internal static let spacing64 = 64
    internal static let spacing68 = 68
    internal static let spacing72 = 72
    internal static let spacing76 = 76
    internal static let spacing8 = 8
    internal static let spacing80 = 80
    internal static let textCaseNone = none
    internal static let textCaseUppercase = uppercase
    internal static let textDecorationNone = none
    internal static let textDecorationUnderline = underline
    internal static let tokenSetOrder0 = globals
    internal static let tokenSetOrder1 = 0-core/__layout
    internal static let tokenSetOrder2 = 0-core/__buttons
    internal static let tokenSetOrder3 = 0-core/__typography
    internal static let tokenSetOrder4 = 1-components
    internal static let xSmallBoldFontFamily = Roboto
    internal static let xSmallBoldFontSize = 10
    internal static let xSmallBoldFontWeight = Bold
    internal static let xSmallBoldLineHeight = 120%
    internal static let xSmallMediumFontFamily = Roboto
    internal static let xSmallMediumFontSize = 10
    internal static let xSmallMediumFontWeight = Medium
    internal static let xSmallMediumLineHeight = 120%
    internal static let xSmallRegularFontFamily = Roboto
    internal static let xSmallRegularFontSize = 10
    internal static let xSmallRegularFontWeight = Regular
    internal static let xSmallRegularLineHeight = 120%
    internal static let xSmallSemiBoldFontFamily = Roboto
    internal static let xSmallSemiBoldFontSize = 10
    internal static let xSmallSemiBoldFontWeight = SemiBold
    internal static let xSmallSemiBoldLineHeight = 120%
}
