
//
// designTokens/ios-swift/DesignSystem+Struct.swift
//

// Do not edit directly
// Generated on Fri, 03 Feb 2023 14:34:03 GMT


import UIKit

internal struct DesignSystemStruct {
    internal static let baseBoldFontFamily = Roboto
    internal static let baseBoldFontSize = 14
    internal static let baseBoldFontWeight = Bold
    internal static let baseBoldLetterSpacing = 0%
    internal static let baseBoldLineHeight = 140%
    internal static let baseBoldParagraphIndent = 0
    internal static let baseBoldParagraphSpacing = 0
    internal static let baseBoldTextCase = none
    internal static let baseBoldTextDecoration = none
    internal static let baseItalicFontFamily = Roboto
    internal static let baseItalicFontSize = 14
    internal static let baseItalicFontWeight = Italic
    internal static let baseItalicLetterSpacing = 0%
    internal static let baseItalicLineHeight = 140%
    internal static let baseItalicParagraphIndent = 0
    internal static let baseItalicParagraphSpacing = 0
    internal static let baseItalicTextCase = none
    internal static let baseItalicTextDecoration = none
    internal static let baseMediumFontFamily = Roboto
    internal static let baseMediumFontSize = 14
    internal static let baseMediumFontWeight = Medium
    internal static let baseMediumLetterSpacing = 0%
    internal static let baseMediumLineHeight = 140%
    internal static let baseMediumParagraphIndent = 0
    internal static let baseMediumParagraphSpacing = 0
    internal static let baseMediumTextCase = none
    internal static let baseMediumTextDecoration = none
    internal static let baseRegularFontFamily = Roboto
    internal static let baseRegularFontSize = 14
    internal static let baseRegularFontWeight = Regular
    internal static let baseRegularLetterSpacing = 0%
    internal static let baseRegularLineHeight = 140%
    internal static let baseRegularParagraphIndent = 0
    internal static let baseRegularParagraphSpacing = 0
    internal static let baseRegularTextCase = none
    internal static let baseRegularTextDecoration = none
    internal static let baseSemiBoldFontFamily = Roboto
    internal static let baseSemiBoldFontSize = 14
    internal static let baseSemiBoldFontWeight = SemiBold
    internal static let baseSemiBoldLetterSpacing = 0%
    internal static let baseSemiBoldLineHeight = 140%
    internal static let baseSemiBoldParagraphIndent = 0
    internal static let baseSemiBoldParagraphSpacing = 0
    internal static let baseSemiBoldTextCase = none
    internal static let baseSemiBoldTextDecoration = none
    internal static let borderRadiusLg = 12
    internal static let borderRadiusMd = 8
    internal static let borderRadiusSm = 4
    internal static let borderRadiusXl = 16
    internal static let borderRadiusXxl = 20
    internal static let borderRadiusXxxl = 24
    internal static let borderWidth1 = 1
    internal static let borderWidth2 = 2
    internal static let buttonPrimaryBackgroundColor = UIColor(red: 0.337, green: 0.710, blue: 0.737, alpha: 1)
    internal static let colorAccentA100 = UIColor(red: 0.616, green: 0.831, blue: 0.847, alpha: 1)
    internal static let colorAccentA200 = UIColor(red: 0.451, green: 0.761, blue: 0.780, alpha: 1)
    internal static let colorAccentA300 = UIColor(red: 0.337, green: 0.710, blue: 0.737, alpha: 1)
    internal static let colorAccentA400 = UIColor(red: 0.235, green: 0.498, blue: 0.518, alpha: 1)
    internal static let colorAccentA50 = UIColor(red: 0.933, green: 0.973, blue: 0.973, alpha: 1)
    internal static let colorAccentA500 = UIColor(red: 0.204, green: 0.431, blue: 0.451, alpha: 1)
    internal static let colorAccentA75 = UIColor(red: 0.729, green: 0.882, blue: 0.894, alpha: 1)
    internal static let colorBlack = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorBody = UIColor(red: 0.024, green: 0.071, blue: 0.086, alpha: 1)
    internal static let colorDangerD100 = UIColor(red: 0.961, green: 0.529, blue: 0.529, alpha: 1)
    internal static let colorDangerD200 = UIColor(red: 0.941, green: 0.325, blue: 0.325, alpha: 1)
    internal static let colorDangerD300 = UIColor(red: 0.929, green: 0.188, blue: 0.188, alpha: 1)
    internal static let colorDangerD400 = UIColor(red: 0.651, green: 0.133, blue: 0.133, alpha: 1)
    internal static let colorDangerD50 = UIColor(red: 0.992, green: 0.918, blue: 0.918, alpha: 1)
    internal static let colorDangerD500 = UIColor(red: 0.569, green: 0.114, blue: 0.114, alpha: 1)
    internal static let colorDangerD75 = UIColor(red: 0.973, green: 0.667, blue: 0.667, alpha: 1)
    internal static let colorInfoI100 = UIColor(red: 0.490, green: 0.808, blue: 0.988, alpha: 1)
    internal static let colorInfoI200 = UIColor(red: 0.267, green: 0.722, blue: 0.980, alpha: 1)
    internal static let colorInfoI300 = UIColor(red: 0.118, green: 0.667, blue: 0.976, alpha: 1)
    internal static let colorInfoI400 = UIColor(red: 0.082, green: 0.467, blue: 0.682, alpha: 1)
    internal static let colorInfoI50 = UIColor(red: 0.914, green: 0.969, blue: 0.996, alpha: 1)
    internal static let colorInfoI500 = UIColor(red: 0.071, green: 0.408, blue: 0.596, alpha: 1)
    internal static let colorInfoI75 = UIColor(red: 0.639, green: 0.863, blue: 0.992, alpha: 1)
    internal static let colorNeutralN0 = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    internal static let colorNeutralN10 = UIColor(red: 0.980, green: 0.980, blue: 0.984, alpha: 1)
    internal static let colorNeutralN100 = UIColor(red: 0.471, green: 0.494, blue: 0.584, alpha: 1)
    internal static let colorNeutralN20 = UIColor(red: 0.961, green: 0.961, blue: 0.969, alpha: 1)
    internal static let colorNeutralN200 = UIColor(red: 0.412, green: 0.439, blue: 0.537, alpha: 1)
    internal static let colorNeutralN30 = UIColor(red: 0.922, green: 0.925, blue: 0.937, alpha: 1)
    internal static let colorNeutralN300 = UIColor(red: 0.353, green: 0.384, blue: 0.490, alpha: 1)
    internal static let colorNeutralN40 = UIColor(red: 0.875, green: 0.878, blue: 0.898, alpha: 1)
    internal static let colorNeutralN400 = UIColor(red: 0.306, green: 0.337, blue: 0.451, alpha: 1)
    internal static let colorNeutralN50 = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    internal static let colorNeutralN500 = UIColor(red: 0.247, green: 0.282, blue: 0.404, alpha: 1)
    internal static let colorNeutralN60 = UIColor(red: 0.698, green: 0.710, blue: 0.761, alpha: 1)
    internal static let colorNeutralN600 = UIColor(red: 0.196, green: 0.235, blue: 0.365, alpha: 1)
    internal static let colorNeutralN70 = UIColor(red: 0.647, green: 0.663, blue: 0.722, alpha: 1)
    internal static let colorNeutralN700 = UIColor(red: 0.129, green: 0.169, blue: 0.314, alpha: 1)
    internal static let colorNeutralN80 = UIColor(red: 0.588, green: 0.608, blue: 0.675, alpha: 1)
    internal static let colorNeutralN800 = UIColor(red: 0.071, green: 0.114, blue: 0.267, alpha: 1)
    internal static let colorNeutralN90 = UIColor(red: 0.529, green: 0.553, blue: 0.627, alpha: 1)
    internal static let colorNeutralN900 = UIColor(red: 0.020, green: 0.067, blue: 0.227, alpha: 1)
    internal static let colorPrimaryP100 = UIColor(red: 0.424, green: 0.545, blue: 0.580, alpha: 1)
    internal static let colorPrimaryP200 = UIColor(red: 0.176, green: 0.349, blue: 0.400, alpha: 1)
    internal static let colorPrimaryP300 = UIColor(red: 0.008, green: 0.216, blue: 0.278, alpha: 1)
    internal static let colorPrimaryP400 = UIColor(red: 0.004, green: 0.153, blue: 0.196, alpha: 1)
    internal static let colorPrimaryP50 = UIColor(red: 0.902, green: 0.922, blue: 0.929, alpha: 1)
    internal static let colorPrimaryP500 = UIColor(red: 0.004, green: 0.133, blue: 0.169, alpha: 1)
    internal static let colorPrimaryP75 = UIColor(red: 0.592, green: 0.678, blue: 0.706, alpha: 1)
    internal static let colorSecondaryS100 = UIColor(red: 0.965, green: 0.737, blue: 0.667, alpha: 1)
    internal static let colorSecondaryS200 = UIColor(red: 0.949, green: 0.624, blue: 0.525, alpha: 1)
    internal static let colorSecondaryS300 = UIColor(red: 0.937, green: 0.545, blue: 0.427, alpha: 1)
    internal static let colorSecondaryS400 = UIColor(red: 0.655, green: 0.380, blue: 0.298, alpha: 1)
    internal static let colorSecondaryS50 = UIColor(red: 0.992, green: 0.953, blue: 0.941, alpha: 1)
    internal static let colorSecondaryS500 = UIColor(red: 0.573, green: 0.333, blue: 0.259, alpha: 1)
    internal static let colorSecondaryS75 = UIColor(red: 0.973, green: 0.812, blue: 0.765, alpha: 1)
    internal static let colorSuccessS100 = UIColor(red: 0.694, green: 0.859, blue: 0.533, alpha: 1)
    internal static let colorSuccessS200 = UIColor(red: 0.565, green: 0.800, blue: 0.329, alpha: 1)
    internal static let colorSuccessS300 = UIColor(red: 0.475, green: 0.757, blue: 0.192, alpha: 1)
    internal static let colorSuccessS400 = UIColor(red: 0.333, green: 0.529, blue: 0.133, alpha: 1)
    internal static let colorSuccessS50 = UIColor(red: 0.949, green: 0.976, blue: 0.918, alpha: 1)
    internal static let colorSuccessS500 = UIColor(red: 0.290, green: 0.463, blue: 0.118, alpha: 1)
    internal static let colorSuccessS75 = UIColor(red: 0.784, green: 0.902, blue: 0.671, alpha: 1)
    internal static let colorWarningW100 = UIColor(red: 1.000, green: 0.859, blue: 0.525, alpha: 1)
    internal static let colorWarningW200 = UIColor(red: 1.000, green: 0.800, blue: 0.322, alpha: 1)
    internal static let colorWarningW300 = UIColor(red: 1.000, green: 0.757, blue: 0.180, alpha: 1)
    internal static let colorWarningW400 = UIColor(red: 0.702, green: 0.529, blue: 0.125, alpha: 1)
    internal static let colorWarningW50 = UIColor(red: 1.000, green: 0.976, blue: 0.918, alpha: 1)
    internal static let colorWarningW500 = UIColor(red: 0.612, green: 0.463, blue: 0.110, alpha: 1)
    internal static let colorWarningW75 = UIColor(red: 1.000, green: 0.902, blue: 0.663, alpha: 1)
    internal static let colorWhite = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    internal static let fontFamilyRoboto = Roboto
    internal static let fontSize0 = 10
    internal static let fontSize1 = 11
    internal static let fontSize10 = 32
    internal static let fontSize2 = 12
    internal static let fontSize3 = 14
    internal static let fontSize4 = 16
    internal static let fontSize5 = 18
    internal static let fontSize6 = 20
    internal static let fontSize7 = 22
    internal static let fontSize8 = 25
    internal static let fontSize9 = 28
    internal static let fontWeightBold = Bold
    internal static let fontWeightItalic = Italic
    internal static let fontWeightMedium = Medium
    internal static let fontWeightRegular = Regular
    internal static let fontWeightSemiBold = SemiBold
    internal static let h1BoldFontFamily = Roboto
    internal static let h1BoldFontSize = 32
    internal static let h1BoldFontWeight = Bold
    internal static let h1BoldLetterSpacing = 0%
    internal static let h1BoldLineHeight = 120%
    internal static let h1BoldParagraphIndent = 0
    internal static let h1BoldParagraphSpacing = 0
    internal static let h1BoldTextCase = none
    internal static let h1BoldTextDecoration = none
    internal static let h1MediumFontFamily = Roboto
    internal static let h1MediumFontSize = 32
    internal static let h1MediumFontWeight = Medium
    internal static let h1MediumLetterSpacing = 0%
    internal static let h1MediumLineHeight = 120%
    internal static let h1MediumParagraphIndent = 0
    internal static let h1MediumParagraphSpacing = 0
    internal static let h1MediumTextCase = none
    internal static let h1MediumTextDecoration = none
    internal static let h1RegularFontFamily = Roboto
    internal static let h1RegularFontSize = 32
    internal static let h1RegularFontWeight = Regular
    internal static let h1RegularLetterSpacing = 0%
    internal static let h1RegularLineHeight = 120%
    internal static let h1RegularParagraphIndent = 0
    internal static let h1RegularParagraphSpacing = 0
    internal static let h1RegularTextCase = none
    internal static let h1RegularTextDecoration = none
    internal static let h1SemiBoldFontFamily = Roboto
    internal static let h1SemiBoldFontSize = 32
    internal static let h1SemiBoldFontWeight = SemiBold
    internal static let h1SemiBoldLetterSpacing = 0%
    internal static let h1SemiBoldLineHeight = 120%
    internal static let h1SemiBoldParagraphIndent = 0
    internal static let h1SemiBoldParagraphSpacing = 0
    internal static let h1SemiBoldTextCase = none
    internal static let h1SemiBoldTextDecoration = none
    internal static let h2BoldFontFamily = Roboto
    internal static let h2BoldFontSize = 28
    internal static let h2BoldFontWeight = Bold
    internal static let h2BoldLetterSpacing = 0%
    internal static let h2BoldLineHeight = 120%
    internal static let h2BoldParagraphIndent = 0
    internal static let h2BoldParagraphSpacing = 0
    internal static let h2BoldTextCase = none
    internal static let h2BoldTextDecoration = none
    internal static let h2MediumFontFamily = Roboto
    internal static let h2MediumFontSize = 28
    internal static let h2MediumFontWeight = Medium
    internal static let h2MediumLetterSpacing = 0%
    internal static let h2MediumLineHeight = 120%
    internal static let h2MediumParagraphIndent = 0
    internal static let h2MediumParagraphSpacing = 0
    internal static let h2MediumTextCase = none
    internal static let h2MediumTextDecoration = none
    internal static let h2RegularFontFamily = Roboto
    internal static let h2RegularFontSize = 28
    internal static let h2RegularFontWeight = Regular
    internal static let h2RegularLetterSpacing = 0%
    internal static let h2RegularLineHeight = 120%
    internal static let h2RegularParagraphIndent = 0
    internal static let h2RegularParagraphSpacing = 0
    internal static let h2RegularTextCase = none
    internal static let h2RegularTextDecoration = none
    internal static let h2SemiBoldFontFamily = Roboto
    internal static let h2SemiBoldFontSize = 28
    internal static let h2SemiBoldFontWeight = SemiBold
    internal static let h2SemiBoldLetterSpacing = 0%
    internal static let h2SemiBoldLineHeight = 120%
    internal static let h2SemiBoldParagraphIndent = 0
    internal static let h2SemiBoldParagraphSpacing = 0
    internal static let h2SemiBoldTextCase = none
    internal static let h2SemiBoldTextDecoration = none
    internal static let h3BoldFontFamily = Roboto
    internal static let h3BoldFontSize = 25
    internal static let h3BoldFontWeight = Bold
    internal static let h3BoldLetterSpacing = 0%
    internal static let h3BoldLineHeight = 120%
    internal static let h3BoldParagraphIndent = 0
    internal static let h3BoldParagraphSpacing = 0
    internal static let h3BoldTextCase = none
    internal static let h3BoldTextDecoration = none
    internal static let h3MediumFontFamily = Roboto
    internal static let h3MediumFontSize = 25
    internal static let h3MediumFontWeight = Medium
    internal static let h3MediumLetterSpacing = 0%
    internal static let h3MediumLineHeight = 120%
    internal static let h3MediumParagraphIndent = 0
    internal static let h3MediumParagraphSpacing = 0
    internal static let h3MediumTextCase = none
    internal static let h3MediumTextDecoration = none
    internal static let h3RegularFontFamily = Roboto
    internal static let h3RegularFontSize = 25
    internal static let h3RegularFontWeight = Regular
    internal static let h3RegularLetterSpacing = 0%
    internal static let h3RegularLineHeight = 120%
    internal static let h3RegularParagraphIndent = 0
    internal static let h3RegularParagraphSpacing = 0
    internal static let h3RegularTextCase = none
    internal static let h3RegularTextDecoration = none
    internal static let h3SemiBoldFontFamily = Roboto
    internal static let h3SemiBoldFontSize = 25
    internal static let h3SemiBoldFontWeight = SemiBold
    internal static let h3SemiBoldLetterSpacing = 0%
    internal static let h3SemiBoldLineHeight = 120%
    internal static let h3SemiBoldParagraphIndent = 0
    internal static let h3SemiBoldParagraphSpacing = 0
    internal static let h3SemiBoldTextCase = none
    internal static let h3SemiBoldTextDecoration = none
    internal static let h4BoldFontFamily = Roboto
    internal static let h4BoldFontSize = 22
    internal static let h4BoldFontWeight = Bold
    internal static let h4BoldLetterSpacing = 0%
    internal static let h4BoldLineHeight = 120%
    internal static let h4BoldParagraphIndent = 0
    internal static let h4BoldParagraphSpacing = 0
    internal static let h4BoldTextCase = none
    internal static let h4BoldTextDecoration = none
    internal static let h4MediumFontFamily = Roboto
    internal static let h4MediumFontSize = 22
    internal static let h4MediumFontWeight = Medium
    internal static let h4MediumLetterSpacing = 0%
    internal static let h4MediumLineHeight = 120%
    internal static let h4MediumParagraphIndent = 0
    internal static let h4MediumParagraphSpacing = 0
    internal static let h4MediumTextCase = none
    internal static let h4MediumTextDecoration = none
    internal static let h4RegularFontFamily = Roboto
    internal static let h4RegularFontSize = 22
    internal static let h4RegularFontWeight = Regular
    internal static let h4RegularLetterSpacing = 0%
    internal static let h4RegularLineHeight = 120%
    internal static let h4RegularParagraphIndent = 0
    internal static let h4RegularParagraphSpacing = 0
    internal static let h4RegularTextCase = none
    internal static let h4RegularTextDecoration = none
    internal static let h4SemiBoldFontFamily = Roboto
    internal static let h4SemiBoldFontSize = 22
    internal static let h4SemiBoldFontWeight = SemiBold
    internal static let h4SemiBoldLetterSpacing = 0%
    internal static let h4SemiBoldLineHeight = 120%
    internal static let h4SemiBoldParagraphIndent = 0
    internal static let h4SemiBoldParagraphSpacing = 0
    internal static let h4SemiBoldTextCase = none
    internal static let h4SemiBoldTextDecoration = none
    internal static let h5BoldFontFamily = Roboto
    internal static let h5BoldFontSize = 20
    internal static let h5BoldFontWeight = Bold
    internal static let h5BoldLetterSpacing = 0%
    internal static let h5BoldLineHeight = 120%
    internal static let h5BoldParagraphIndent = 0
    internal static let h5BoldParagraphSpacing = 0
    internal static let h5BoldTextCase = none
    internal static let h5BoldTextDecoration = none
    internal static let h5ItalicFontFamily = Roboto
    internal static let h5ItalicFontSize = 20
    internal static let h5ItalicFontWeight = Italic
    internal static let h5ItalicLetterSpacing = 0%
    internal static let h5ItalicLineHeight = 120%
    internal static let h5ItalicParagraphIndent = 0
    internal static let h5ItalicParagraphSpacing = 0
    internal static let h5ItalicTextCase = none
    internal static let h5ItalicTextDecoration = none
    internal static let h5MediumFontFamily = Roboto
    internal static let h5MediumFontSize = 20
    internal static let h5MediumFontWeight = Medium
    internal static let h5MediumLetterSpacing = 0%
    internal static let h5MediumLineHeight = 120%
    internal static let h5MediumParagraphIndent = 0
    internal static let h5MediumParagraphSpacing = 0
    internal static let h5MediumTextCase = none
    internal static let h5MediumTextDecoration = none
    internal static let h5RegularFontFamily = Roboto
    internal static let h5RegularFontSize = 20
    internal static let h5RegularFontWeight = Regular
    internal static let h5RegularLetterSpacing = 0%
    internal static let h5RegularLineHeight = 120%
    internal static let h5RegularParagraphIndent = 0
    internal static let h5RegularParagraphSpacing = 0
    internal static let h5RegularTextCase = none
    internal static let h5RegularTextDecoration = none
    internal static let h5SemiBoldFontFamily = Roboto
    internal static let h5SemiBoldFontSize = 20
    internal static let h5SemiBoldFontWeight = SemiBold
    internal static let h5SemiBoldLetterSpacing = 0%
    internal static let h5SemiBoldLineHeight = 120%
    internal static let h5SemiBoldParagraphIndent = 0
    internal static let h5SemiBoldParagraphSpacing = 0
    internal static let h5SemiBoldTextCase = none
    internal static let h5SemiBoldTextDecoration = none
    internal static let h6BoldFontFamily = Roboto
    internal static let h6BoldFontSize = 18
    internal static let h6BoldFontWeight = Bold
    internal static let h6BoldLetterSpacing = 0%
    internal static let h6BoldLineHeight = 120%
    internal static let h6BoldParagraphIndent = 0
    internal static let h6BoldParagraphSpacing = 0
    internal static let h6BoldTextCase = none
    internal static let h6BoldTextDecoration = none
    internal static let h6ItalicFontFamily = Roboto
    internal static let h6ItalicFontSize = 18
    internal static let h6ItalicFontWeight = Italic
    internal static let h6ItalicLetterSpacing = 0%
    internal static let h6ItalicLineHeight = 120%
    internal static let h6ItalicParagraphIndent = 0
    internal static let h6ItalicParagraphSpacing = 0
    internal static let h6ItalicTextCase = none
    internal static let h6ItalicTextDecoration = none
    internal static let h6MediumFontFamily = Roboto
    internal static let h6MediumFontSize = 18
    internal static let h6MediumFontWeight = Medium
    internal static let h6MediumLetterSpacing = 0%
    internal static let h6MediumLineHeight = 120%
    internal static let h6MediumParagraphIndent = 0
    internal static let h6MediumParagraphSpacing = 0
    internal static let h6MediumTextCase = none
    internal static let h6MediumTextDecoration = none
    internal static let h6RegularFontFamily = Roboto
    internal static let h6RegularFontSize = 18
    internal static let h6RegularFontWeight = Regular
    internal static let h6RegularLetterSpacing = 0%
    internal static let h6RegularLineHeight = 120%
    internal static let h6RegularParagraphIndent = 0
    internal static let h6RegularParagraphSpacing = 0
    internal static let h6RegularTextCase = none
    internal static let h6RegularTextDecoration = none
    internal static let h6SemiBoldFontFamily = Roboto
    internal static let h6SemiBoldFontSize = 18
    internal static let h6SemiBoldFontWeight = SemiBold
    internal static let h6SemiBoldLetterSpacing = 0%
    internal static let h6SemiBoldLineHeight = 120%
    internal static let h6SemiBoldParagraphIndent = 0
    internal static let h6SemiBoldParagraphSpacing = 0
    internal static let h6SemiBoldTextCase = none
    internal static let h6SemiBoldTextDecoration = none
    internal static let labelBoldFontFamily = Roboto
    internal static let labelBoldFontSize = 11
    internal static let labelBoldFontWeight = Bold
    internal static let labelBoldLetterSpacing = 0%
    internal static let labelBoldLineHeight = 120%
    internal static let labelBoldParagraphIndent = 0
    internal static let labelBoldParagraphSpacing = 0
    internal static let labelBoldTextCase = none
    internal static let labelBoldTextDecoration = none
    internal static let labelItalicFontFamily = Roboto
    internal static let labelItalicFontSize = 11
    internal static let labelItalicFontWeight = Italic
    internal static let labelItalicLetterSpacing = 0%
    internal static let labelItalicLineHeight = 120%
    internal static let labelItalicParagraphIndent = 0
    internal static let labelItalicParagraphSpacing = 0
    internal static let labelItalicTextCase = none
    internal static let labelItalicTextDecoration = none
    internal static let labelMediumFontFamily = Roboto
    internal static let labelMediumFontSize = 11
    internal static let labelMediumFontWeight = Medium
    internal static let labelMediumLetterSpacing = 0%
    internal static let labelMediumLineHeight = 120%
    internal static let labelMediumParagraphIndent = 0
    internal static let labelMediumParagraphSpacing = 0
    internal static let labelMediumTextCase = none
    internal static let labelMediumTextDecoration = none
    internal static let labelRegularFontFamily = Roboto
    internal static let labelRegularFontSize = 11
    internal static let labelRegularFontWeight = Regular
    internal static let labelRegularLetterSpacing = 0%
    internal static let labelRegularLineHeight = 120%
    internal static let labelRegularParagraphIndent = 0
    internal static let labelRegularParagraphSpacing = 0
    internal static let labelRegularTextCase = none
    internal static let labelRegularTextDecoration = none
    internal static let labelSemiBoldFontFamily = Roboto
    internal static let labelSemiBoldFontSize = 11
    internal static let labelSemiBoldFontWeight = SemiBold
    internal static let labelSemiBoldLetterSpacing = 0%
    internal static let labelSemiBoldLineHeight = 120%
    internal static let labelSemiBoldParagraphIndent = 0
    internal static let labelSemiBoldParagraphSpacing = 0
    internal static let labelSemiBoldTextCase = none
    internal static let labelSemiBoldTextDecoration = none
    internal static let largeBoldFontFamily = Roboto
    internal static let largeBoldFontSize = 16
    internal static let largeBoldFontWeight = Bold
    internal static let largeBoldLetterSpacing = 0%
    internal static let largeBoldLineHeight = 120%
    internal static let largeBoldParagraphIndent = 0
    internal static let largeBoldParagraphSpacing = 0
    internal static let largeBoldTextCase = none
    internal static let largeBoldTextDecoration = none
    internal static let largeItalicFontFamily = Roboto
    internal static let largeItalicFontSize = 16
    internal static let largeItalicFontWeight = Italic
    internal static let largeItalicLetterSpacing = 0%
    internal static let largeItalicLineHeight = 120%
    internal static let largeItalicParagraphIndent = 0
    internal static let largeItalicParagraphSpacing = 0
    internal static let largeItalicTextCase = none
    internal static let largeItalicTextDecoration = none
    internal static let largeMediumFontFamily = Roboto
    internal static let largeMediumFontSize = 16
    internal static let largeMediumFontWeight = Medium
    internal static let largeMediumLetterSpacing = 0%
    internal static let largeMediumLineHeight = 120%
    internal static let largeMediumParagraphIndent = 0
    internal static let largeMediumParagraphSpacing = 0
    internal static let largeMediumTextCase = none
    internal static let largeMediumTextDecoration = none
    internal static let largeRegularFontFamily = Roboto
    internal static let largeRegularFontSize = 16
    internal static let largeRegularFontWeight = Regular
    internal static let largeRegularLetterSpacing = 0%
    internal static let largeRegularLineHeight = 120%
    internal static let largeRegularParagraphIndent = 0
    internal static let largeRegularParagraphSpacing = 0
    internal static let largeRegularTextCase = none
    internal static let largeRegularTextDecoration = none
    internal static let largeSemiBoldFontFamily = Roboto
    internal static let largeSemiBoldFontSize = 16
    internal static let largeSemiBoldFontWeight = SemiBold
    internal static let largeSemiBoldLetterSpacing = 0%
    internal static let largeSemiBoldLineHeight = 120%
    internal static let largeSemiBoldParagraphIndent = 0
    internal static let largeSemiBoldParagraphSpacing = 0
    internal static let largeSemiBoldTextCase = none
    internal static let largeSemiBoldTextDecoration = none
    internal static let letterSpacing0 = 0%
    internal static let lineHeight120 = 120%
    internal static let lineHeight140 = 140%
    internal static let opacity10 = 10%
    internal static let opacity100 = 100%
    internal static let opacity20 = 20%
    internal static let opacity30 = 30%
    internal static let opacity40 = 40%
    internal static let opacity50 = 50%
    internal static let opacity60 = 60%
    internal static let opacity70 = 70%
    internal static let opacity80 = 80%
    internal static let opacity90 = 90%
    internal static let paragraphIndent0 = 0
    internal static let paragraphSpacing0 = 0
    internal static let size400 = CGFloat(6400.00)
    internal static let size500 = CGFloat(8000.00)
    internal static let size600 = CGFloat(9600.00)
    internal static let size700 = CGFloat(11200.00)
    internal static let size800 = CGFloat(12800.00)
    internal static let size900 = CGFloat(14400.00)
    internal static let smallBoldFontFamily = Roboto
    internal static let smallBoldFontSize = 12
    internal static let smallBoldFontWeight = Bold
    internal static let smallBoldLetterSpacing = 0%
    internal static let smallBoldLineHeight = 140%
    internal static let smallBoldParagraphIndent = 0
    internal static let smallBoldParagraphSpacing = 0
    internal static let smallBoldTextCase = none
    internal static let smallBoldTextDecoration = none
    internal static let smallItalicFontFamily = Roboto
    internal static let smallItalicFontSize = 12
    internal static let smallItalicFontWeight = Italic
    internal static let smallItalicLetterSpacing = 0%
    internal static let smallItalicLineHeight = 140%
    internal static let smallItalicParagraphIndent = 0
    internal static let smallItalicParagraphSpacing = 0
    internal static let smallItalicTextCase = none
    internal static let smallItalicTextDecoration = none
    internal static let smallMediumFontFamily = Roboto
    internal static let smallMediumFontSize = 12
    internal static let smallMediumFontWeight = Medium
    internal static let smallMediumLetterSpacing = 0%
    internal static let smallMediumLineHeight = 140%
    internal static let smallMediumParagraphIndent = 0
    internal static let smallMediumParagraphSpacing = 0
    internal static let smallMediumTextCase = none
    internal static let smallMediumTextDecoration = none
    internal static let smallRegularFontFamily = Roboto
    internal static let smallRegularFontSize = 12
    internal static let smallRegularFontWeight = Regular
    internal static let smallRegularLetterSpacing = 0%
    internal static let smallRegularLineHeight = 140%
    internal static let smallRegularParagraphIndent = 0
    internal static let smallRegularParagraphSpacing = 0
    internal static let smallRegularTextCase = none
    internal static let smallRegularTextDecoration = none
    internal static let smallSemiBoldFontFamily = Roboto
    internal static let smallSemiBoldFontSize = 12
    internal static let smallSemiBoldFontWeight = SemiBold
    internal static let smallSemiBoldLetterSpacing = 0%
    internal static let smallSemiBoldLineHeight = 140%
    internal static let smallSemiBoldParagraphIndent = 0
    internal static let smallSemiBoldParagraphSpacing = 0
    internal static let smallSemiBoldTextCase = none
    internal static let smallSemiBoldTextDecoration = none
    internal static let spacing12 = 12
    internal static let spacing16 = 16
    internal static let spacing2 = 2
    internal static let spacing20 = 20
    internal static let spacing24 = 24
    internal static let spacing28 = 28
    internal static let spacing32 = 32
    internal static let spacing36 = 36
    internal static let spacing4 = 4
    internal static let spacing40 = 40
    internal static let spacing44 = 44
    internal static let spacing48 = 48
    internal static let spacing52 = 52
    internal static let spacing56 = 56
    internal static let spacing60 = 60
    internal static let spacing64 = 64
    internal static let spacing68 = 68
    internal static let spacing72 = 72
    internal static let spacing76 = 76
    internal static let spacing8 = 8
    internal static let spacing80 = 80
    internal static let textCaseNone = none
    internal static let textCaseUppercase = uppercase
    internal static let textDecorationNone = none
    internal static let textDecorationUnderline = underline
    internal static let tokenSetOrder0 = core
    internal static let xSmallBoldFontFamily = Roboto
    internal static let xSmallBoldFontSize = 10
    internal static let xSmallBoldFontWeight = Bold
    internal static let xSmallBoldLetterSpacing = 0%
    internal static let xSmallBoldLineHeight = 120%
    internal static let xSmallBoldParagraphIndent = 0
    internal static let xSmallBoldParagraphSpacing = 0
    internal static let xSmallBoldTextCase = none
    internal static let xSmallBoldTextDecoration = none
    internal static let xSmallItalicFontFamily = Roboto
    internal static let xSmallItalicFontSize = 10
    internal static let xSmallItalicFontWeight = Italic
    internal static let xSmallItalicLetterSpacing = 0%
    internal static let xSmallItalicLineHeight = 120%
    internal static let xSmallItalicParagraphIndent = 0
    internal static let xSmallItalicParagraphSpacing = 0
    internal static let xSmallItalicTextCase = none
    internal static let xSmallItalicTextDecoration = none
    internal static let xSmallMediumFontFamily = Roboto
    internal static let xSmallMediumFontSize = 10
    internal static let xSmallMediumFontWeight = Medium
    internal static let xSmallMediumLetterSpacing = 0%
    internal static let xSmallMediumLineHeight = 120%
    internal static let xSmallMediumParagraphIndent = 0
    internal static let xSmallMediumParagraphSpacing = 0
    internal static let xSmallMediumTextCase = none
    internal static let xSmallMediumTextDecoration = none
    internal static let xSmallRegularFontFamily = Roboto
    internal static let xSmallRegularFontSize = 10
    internal static let xSmallRegularFontWeight = Regular
    internal static let xSmallRegularLetterSpacing = 0%
    internal static let xSmallRegularLineHeight = 120%
    internal static let xSmallRegularParagraphIndent = 0
    internal static let xSmallRegularParagraphSpacing = 0
    internal static let xSmallRegularTextCase = none
    internal static let xSmallRegularTextDecoration = none
    internal static let xSmallSemiBoldFontFamily = Roboto
    internal static let xSmallSemiBoldFontSize = 10
    internal static let xSmallSemiBoldFontWeight = SemiBold
    internal static let xSmallSemiBoldLetterSpacing = 0%
    internal static let xSmallSemiBoldLineHeight = 120%
    internal static let xSmallSemiBoldParagraphIndent = 0
    internal static let xSmallSemiBoldParagraphSpacing = 0
    internal static let xSmallSemiBoldTextCase = none
    internal static let xSmallSemiBoldTextDecoration = none
}
